(function(){
  'use strict';

  const KEY='vesa.app.preferences.v1';
  const AQL_KEY='vesa360-personal-appearance-v1';
  const LANG_KEYS=['vesa.app.language','vesa-guide-language','vesa.ppm.language'];
  const THEMES={
    'clear-blue':{name:'Clear Blue',note:'White / blue',dark:false,canvas:'#f3f6fa',paper:'#ffffff',surface:'#eef3f9',ink:'#17263d',muted:'#526176',line:'#cbd6e4',accent:'#244fd6',soft:'#eaf0ff',on:'#ffffff',sidebar:'#071a35',sideInk:'#ffffff',sideMuted:'#c8d6e3',sideActive:'#132b4b',sideAccent:'#7ea6ff',field:'#ffffff'},
    'pure-mono':{name:'Pure Mono',note:'White / black',dark:false,canvas:'#f3f3f3',paper:'#ffffff',surface:'#eeeeef',ink:'#202124',muted:'#585b62',line:'#c9cbcf',accent:'#202124',soft:'#e9e9eb',on:'#ffffff',sidebar:'#111316',sideInk:'#f2f4f7',sideMuted:'#c9ccd2',sideActive:'#2b2f34',sideAccent:'#ffffff',field:'#ffffff'},
    'midnight-mono':{name:'Midnight Mono',note:'Black / white',dark:true,canvas:'#101214',paper:'#191c20',surface:'#252a31',ink:'#f2f4f7',muted:'#b4bdc9',line:'#48515e',accent:'#f0f2f5',soft:'#303741',on:'#14171a',sidebar:'#0b0d10',sideInk:'#e3e8ee',sideMuted:'#aeb9c8',sideActive:'#2b333e',sideAccent:'#f0f2f5',field:'#14181e'},
    'forest-yellow':{name:'Forest Yellow',note:'Deep green / yellow',dark:true,canvas:'#0e211b',paper:'#173128',surface:'#203d31',ink:'#f4f7ed',muted:'#bfcec4',line:'#4c6758',accent:'#f5d66f',soft:'#394633',on:'#223221',sidebar:'#091b15',sideInk:'#e5eddb',sideMuted:'#b9cbbb',sideActive:'#324534',sideAccent:'#f5d66f',field:'#10271f'},
    'warm-ivory':{name:'Warm Ivory',note:'Ivory / walnut',dark:false,canvas:'#f4f0e7',paper:'#fffcf6',surface:'#eee8dc',ink:'#302a23',muted:'#6d6153',line:'#d7cbb9',accent:'#765338',soft:'#eee3d6',on:'#fffdf8',sidebar:'#3b332b',sideInk:'#f5ebdb',sideMuted:'#d0c0ac',sideActive:'#544638',sideAccent:'#ffdfb7',field:'#fffefb'}
  };
  const DEFAULT={theme:'clear-blue',language:'en',density:'comfortable',font:'modern'};
  const LABELS={
    en:{language:'Language',appearance:'Appearance',theme:'Theme',login:'Login',userId:'User ID',password:'Password',demo:'Demo access: admin@vesa / vesa or user@vesa / vesa.',appCentre:'App Centre',choose:'Choose Your Workspace',chooseText:'Open the approved VESA tools for local forms, calculations, saved copies and reports.',openAql:'Open AQL',openPpm:'Open PPM',admin:'Admin',logout:'Logout',saved:'Preferences saved for this browser.'},
    ta:{language:'மொழி',appearance:'தோற்றம்',theme:'நிறம்',login:'Login',userId:'User ID',password:'Password',demo:'Demo access: admin@vesa / vesa அல்லது user@vesa / vesa.',appCentre:'App Centre',choose:'Workspace தேர்வு செய்யவும்',chooseText:'Local forms, calculations, saved copies மற்றும் reports க்கான approved VESA tools திறக்கவும்.',openAql:'AQL திறக்கவும்',openPpm:'PPM திறக்கவும்',admin:'Admin',logout:'Logout',saved:'இந்த browser-க்கு preference save ஆனது.'},
    bn:{language:'Language',appearance:'Appearance',theme:'Theme',login:'Login',userId:'User ID',password:'Password',demo:'Demo access: admin@vesa / vesa অথবা user@vesa / vesa.',appCentre:'App Centre',choose:'Workspace নির্বাচন করুন',chooseText:'Local forms, calculations, saved copies এবং reports-এর approved VESA tools খুলুন.',openAql:'AQL খুলুন',openPpm:'PPM খুলুন',admin:'Admin',logout:'Logout',saved:'এই browser-এ preference saved.'},
    hi:{language:'Language',appearance:'Appearance',theme:'Theme',login:'Login',userId:'User ID',password:'Password',demo:'Demo access: admin@vesa / vesa या user@vesa / vesa.',appCentre:'App Centre',choose:'Workspace चुनें',chooseText:'Local forms, calculations, saved copies और reports के approved VESA tools खोलें.',openAql:'AQL खोलें',openPpm:'PPM खोलें',admin:'Admin',logout:'Logout',saved:'इस browser में preference saved.'}
  };
  const clean=value=>String(value||'').trim();
  function getItem(key){try{return localStorage.getItem(key)}catch{return null}}
  function setItem(key,value){try{localStorage.setItem(key,value)}catch{}}
  function readJson(key){try{return JSON.parse(localStorage.getItem(key)||'null')}catch{return null}}
  function aqlSeed(){const raw=readJson(AQL_KEY);return raw&&raw.version===1&&raw.settings?raw.settings:null}
  function normalize(value){
    const seed=aqlSeed()||{};
    const v=value&&typeof value==='object'?value:{};
    const lang=clean(v.language||getItem('vesa.app.language')||getItem('vesa-guide-language')||getItem('vesa.ppm.language')||DEFAULT.language);
    return {theme:THEMES[v.theme]?v.theme:(THEMES[seed.theme]?seed.theme:DEFAULT.theme),language:['en','ta','bn','hi'].includes(lang)?lang:DEFAULT.language,density:['compact','comfortable','touch'].includes(v.density)?v.density:(['compact','comfortable','touch'].includes(seed.density)?seed.density:DEFAULT.density),font:['modern','classic','spacious','editorial'].includes(v.font)?v.font:(['modern','classic','spacious','editorial'].includes(seed.font)?seed.font:DEFAULT.font)};
  }
  function read(){return normalize(readJson(KEY));}
  function write(settings){const s=normalize(settings);setItem(KEY,JSON.stringify({version:1,settings:s,updatedAt:new Date().toISOString()}));LANG_KEYS.forEach(k=>setItem(k,s.language));setItem(AQL_KEY,JSON.stringify({version:1,settings:{theme:s.theme,followDevice:false,font:s.font,text:'standard',density:s.density,layout:'guided',striping:true,stickyColumns:true,motion:'system',reportStyle:'classic',reportFont:'classic',reportSize:'standard',reportSpacing:'comfortable',reportAccent:'blue'}}));return s;}
  function tokens(theme){const t=THEMES[theme]||THEMES[DEFAULT.theme];return {'--canvas':t.canvas,'--paper':t.paper,'--look-surface':t.surface,'--ink':t.ink,'--muted':t.muted,'--line':t.line,'--blue':t.accent,'--blue-light':t.soft,'--look-on-accent':t.on,'--look-sidebar':t.sidebar,'--look-side-ink':t.sideInk,'--look-side-muted':t.sideMuted,'--look-side-active':t.sideActive,'--look-side-accent':t.sideAccent,'--look-field':t.field,'--navy':t.sidebar,'--navy2':t.sideActive,'--teal':t.accent,'--teal2':t.accent,'--gold':t.accent,'--cream':t.canvas,'--ice':t.surface,'--ok':t.dark?'#9ce7c2':'#12633f','--okbg':t.dark?'#193b2c':'#e9f6ef','--action':t.dark?'#ffbdc9':'#a22643','--actionbg':t.dark?'#42222d':'#fceef1','--pending':t.dark?'#ffe09d':'#81520c','--pendingbg':t.dark?'#3d311a':'#fff4df','--shadow':t.dark?'0 16px 52px #0000003b':'0 14px 42px #2537560d'};}
  function fontStack(font){return ({modern:'"Segoe UI",Arial,system-ui,sans-serif',classic:'Arial,Helvetica,sans-serif',spacious:'Verdana,Geneva,sans-serif',editorial:'Arial,Helvetica,sans-serif'}[font]||'"Segoe UI",Arial,system-ui,sans-serif');}
  function apply(input){const s=normalize(input||read());const t=THEMES[s.theme],root=document.documentElement;root.dataset.vesaTheme=s.theme;root.dataset.dark=String(t.dark);root.dataset.density=s.density;root.lang=s.language;for(const [k,v] of Object.entries(tokens(s.theme)))root.style.setProperty(k,v);root.style.setProperty('--ui',fontStack(s.font));root.style.setProperty('--heading-font',s.font==='editorial'?'Georgia,"Times New Roman",serif':fontStack(s.font));document.querySelector('meta[name="theme-color"]')?.setAttribute('content',t.canvas);return s;}
  function label(key){const s=read();return (LABELS[s.language]||LABELS.en)[key]||LABELS.en[key]||key;}
  function translate(){const dict=LABELS[read().language]||LABELS.en;document.querySelectorAll('[data-i18n]').forEach(el=>{const key=el.dataset.i18n;if(dict[key])el.textContent=dict[key];});document.querySelectorAll('[data-i18n-placeholder]').forEach(el=>{const key=el.dataset.i18nPlaceholder;if(dict[key])el.setAttribute('placeholder',dict[key]);});}
  function notifyApps(s){try{if(globalThis.app?.locale?.set){globalThis.app.locale.set(s.language);globalThis.app.render?.();}}catch{}}
  function controls(){const s=read();return `<div class="vesa-pref-controls" data-vesa-pref-controls><label>${label('language')}<select data-pref-language><option value="en">English</option><option value="ta">Tamil</option><option value="bn">Bengali</option><option value="hi">Hindi</option></select></label><label>${label('theme')}<select data-pref-theme>${Object.entries(THEMES).map(([k,v])=>`<option value="${k}">${v.name}</option>`).join('')}</select></label></div>`;}
  function wire(root=document){root.querySelectorAll('[data-pref-language]').forEach(el=>{el.value=read().language;el.onchange=()=>{const s=write({...read(),language:el.value});apply(s);translate();syncControls();notifyApps(s);window.dispatchEvent(new CustomEvent('vesa-preferences-change',{detail:s}));};});root.querySelectorAll('[data-pref-theme]').forEach(el=>{el.value=read().theme;el.onchange=()=>{const s=write({...read(),theme:el.value});apply(s);translate();syncControls();notifyApps(s);window.dispatchEvent(new CustomEvent('vesa-preferences-change',{detail:s}));};});}
  function syncControls(){document.querySelectorAll('[data-pref-language]').forEach(el=>el.value=read().language);document.querySelectorAll('[data-pref-theme]').forEach(el=>el.value=read().theme);}
  function mount(){apply(write(read()));translate();document.querySelectorAll('[data-vesa-preferences]').forEach(el=>{if(!el.querySelector('[data-vesa-pref-controls]')){el.insertAdjacentHTML('beforeend',controls());wire(el);}});const addBar=()=>{const bar=document.querySelector('.app-user-bar');if(bar&&!bar.querySelector('[data-vesa-pref-controls]')){bar.insertAdjacentHTML('beforeend',controls());wire(bar);}};addBar();new MutationObserver(addBar).observe(document.body,{childList:true,subtree:true});}
  window.VesaPrefs={KEY,THEMES,LABELS,read,write,apply,label,translate,controls,wire,mount};
  apply(read());
  if(document.readyState==='loading')document.addEventListener('DOMContentLoaded',mount);else mount();
})();
