/** Planning feature proof. Access: NODE_PATH=<runtime modules> CHROMIUM_PATH=<binary>
 * node apps/ppm/tests/planning.cjs. Owns synthetic records and disposable browser/server;
 * never reads production records. Domain checks precede real forms/reload/export checks. */
const fs=require('fs'),path=require('path'),http=require('http'),vm=require('vm'),assert=require('assert/strict');
const {chromium}=require('playwright');
class PlanningRegression {
  constructor(){this.root=path.resolve(__dirname,'../../..');this.passes=[];this.errors=[]}
  pass(name){this.passes.push(name);console.log('PASS',name)}
  /** Sandbox class declarations only; no workspace startup or external state. */
  domain(){const context=vm.createContext({console,crypto:require('crypto').webcrypto,structuredClone,Date,window:{},document:{},setTimeout,clearTimeout,atob});for(const f of ['core.js','planning-services.js','record-services.js'])vm.runInContext(fs.readFileSync(path.join(this.root,'apps/ppm',f),'utf8'),context);const C=vm.runInContext('({MeasurementCheck,ApprovalRegister,PlanningService,ChangeReviewEngine,BackupCodec,PpmRecordFactory,ValidationEngine,RelevanceEngine,CoverageEngine})',context),check=new C.MeasurementCheck(),row={spec:'50',actual:'51',tol:'±1',unit:'cm'};
    assert.equal(check.compare(row).status,'Within tolerance');assert.equal(check.compare({...row,actual:'51.00001'}).status,'Outside tolerance');assert.equal(check.compare({...row,actual:'49'}).status,'Within tolerance');assert.equal(check.compare({...row,actual:'48.99'}).status,'Outside tolerance');assert.equal(check.compare({...row,actual:'50',tol:'0'}).status,'Within tolerance');assert.equal(check.compare({...row,actual:'',tol:'1'}).status,'Not checked');for(const change of [{tol:''},{unit:''},{unit:'mm'},{spec:'50cm'},{actual:'NaN'},{actual:'-1'},{actual:'1e3'},{tol:'-1'},{tolMinus:'1',tolPlus:''}])assert.equal(check.compare({...row,...change}).status,'Check entries');assert.equal(check.compare({...row,actual:'49.5',tolMinus:'.5',tolPlus:'1.5'}).status,'Within tolerance');assert.equal(check.compare({...row,actual:'49.49',tolMinus:'.5',tolPlus:'1.5'}).status,'Outside tolerance');assert.equal(check.compare({spec:'0.1',actual:'0.3',tol:'0.2',unit:'in'}).status,'Within tolerance');this.pass('measurement boundaries, zero/asymmetric tolerances, units and invalid numbers');
    const planner=new C.PlanningService(),record=C.PpmRecordFactory.create(),a=C.ApprovalRegister.create('PP sample');record.approvals=[a];assert.equal(planner.readiness(record).ready,false);a.status='Approved';a.approvedBy='QA';a.date='2026-10-07';assert.equal(planner.readiness(record).ready,false);a.reference='Buyer email';assert.equal(planner.readiness(record).ready,true);a.status='Not needed';a.reference='';assert.equal(planner.readiness(record).ready,false);a.notes='Buyer confirmed not needed';assert.equal(planner.readiness(record).ready,true);a.status='Rejected';a.required=false;assert.equal(planner.readiness(record).ready,true);this.pass('required approvals need status, named/date proof or documented exemption');
    planner.changes.review(record,'QA');record.meta.fabricWeight='180 GSM';assert.equal(planner.changes.diff(record).length,1);record.release.decision='GO';record.signatures.factory={image:'old'};assert.equal(planner.invalidate(record),true);assert.equal(record.release.decision,'');assert.equal(Object.keys(record.signatures).length,0);assert.equal(planner.readiness(record).ready,false);planner.changes.review(record,'QA','Rechecked');assert.equal(planner.readiness(record).ready,true);assert.equal(record.changeReview.history[1].changes[0].before,'');assert.equal(record.changeReview.history[1].changes[0].after,'180 GSM');record.meta.processes=['print','garmentWash'];planner.changes.review(record,'QA');record.meta.processes.reverse();assert.equal(planner.changes.diff(record).length,0);this.pass('reviewed changes, fresh sign-off invalidation, history and process ordering');
    const ready=C.PpmRecordFactory.create();Object.assign(ready.meta,{factory:'F',buyer:'B',style:'S',construction:'knit',techPackRev:'R1'});ready.release.notes='Written conditions';ready.signatures.factory={image:'proof',name:'Factory QA',date:'2026-10-07'};ready.signatures.buyer={image:'proof',name:'Buyer QA',date:'2026-10-07'};const validation=new C.ValidationEngine(new C.RelevanceEngine(),{compute(){return {coverage:100,closure:100,criticalBlockers:0,pending:0}}},planner);assert.equal(validation.readiness(ready).go,true);ready.approvals=[C.ApprovalRegister.create('Fabric')];assert.equal(validation.readiness(ready).go,false);assert.equal(validation.readiness(ready).conditional,false);ready.approvals=[];ready.measurements[0]={...C.PpmRecordFactory.measurement(),spec:'50',actual:'51.1',tol:'1',unit:'cm',checkRequired:true};assert.equal(validation.readiness(ready).go,false);ready.measurements[0].actual='51';assert.equal(validation.readiness(ready).go,true);planner.changes.review(ready,'QA');ready.meta.bomRev='R2';assert.equal(validation.readiness(ready).go,false);assert.equal(validation.readiness(ready).conditional,false);for(let i=0;i<12;i++){planner.changes.review(ready,'QA');ready.meta.bomRev='R'+i}assert.equal(ready.changeReview.history.length,10);this.pass('GO/Conditional gates and bounded review history');
    record.customCheckpoints=[{id:'CUST-'+require('crypto').randomUUID(),section:'order',label:'Buyer-specific check',hint:'Approved instruction',critical:true}];assert.ok(planner.changes.diff(record).some(d=>d.key.startsWith('custom.')));planner.changes.review(record,'QA');record.customCheckpoints[0].hint='Revised instruction';assert.ok(planner.changes.diff(record).some(d=>d.key.endsWith('.hint')));planner.changes.review(record,'QA');this.pass('custom production instructions participate in reviewed changes');
    const codec=new C.BackupCodec(),copy=codec.decode(JSON.parse(codec.encode(record)));assert.equal(copy.approvals[0].notes,'Buyer confirmed not needed');assert.equal(copy.changeReview.baseline.reviewer,'QA');assert.equal(JSON.parse(codec.encode(record)).schema,2);const legacy=JSON.parse(JSON.stringify(record));delete legacy.approvals;delete legacy.changeReview;legacy.measurements=legacy.measurements.map(({pom,spec,tol,method,risk,remark})=>({pom,spec,tol,method,risk,remark}));legacy.version='4.1.1';const migrated=codec.decode(legacy);assert.equal(migrated.approvals.length,0);assert.equal(migrated.changeReview.baseline,null);assert.equal(migrated.measurements[0].checkRequired,false);this.pass('schema-2 planning roundtrip and V4 additive migration');
    const bad=[r=>r.approvals.push({...r.approvals[0]}),r=>r.approvals[0].required='true',r=>r.approvals[0].date='2026-99-99',r=>r.approvals[0].photo='data:image/svg+xml;base64,PHN2Zz4=',r=>r.measurements[0].unit='mm',r=>r.measurements[0].actual=0,r=>r.changeReview.baseline.values.push({key:'__proto__.bad',value:'bad'}),r=>r.changeReview.baseline.values.push(r.changeReview.baseline.values[0]),r=>r.changeReview.history[0].count=-1];for(const mutate of bad){const r=JSON.parse(JSON.stringify(record));mutate(r);assert.throws(()=>codec.decode(r))}this.pass('malformed approvals, units, photos, dates and history rejected atomically');
  }
  async start(){this.server=http.createServer((req,res)=>{const url=new URL(req.url,'http://test');let file=path.join(this.root,decodeURIComponent(url.pathname));if(!file.startsWith(this.root+path.sep)){res.writeHead(403).end();return}try{if(fs.statSync(file).isDirectory())file=path.join(file,'index.html');res.setHeader('Content-Type',({'.html':'text/html','.js':'application/javascript','.css':'text/css','.ttf':'font/ttf','.png':'image/png','.webmanifest':'application/manifest+json'})[path.extname(file)]||'application/octet-stream');res.end(fs.readFileSync(file))}catch{res.writeHead(404).end()}});await new Promise(r=>this.server.listen(0,'127.0.0.1',r));this.url=`http://127.0.0.1:${this.server.address().port}/apps/ppm/`;this.browser=await chromium.launch({executablePath:process.env.CHROMIUM_PATH,headless:true,args:['--no-sandbox','--disable-dev-shm-usage']});this.context=await this.browser.newContext({viewport:{width:390,height:844}});this.page=await this.context.newPage();this.page.on('pageerror',e=>this.errors.push(e.message));await this.page.goto(this.url);await this.page.waitForFunction(()=>typeof app!=='undefined'&&document.body.classList.contains('at-home'))}
  async run(){this.domain();await this.start();const p=this.page;await p.locator('#homeScreen [data-command="new"]').click();await p.locator('.identity-field [data-bind="meta.style"]').fill('PLANNING-QA');await p.evaluate(()=>app.command('approvals'));await p.locator('#newApprovalLabel').fill('PP sample');await p.locator('[data-plan-action="add-approval"]').click();await p.locator('[data-approval-field="0.status"]').selectOption('Approved');await p.locator('[data-approval-field="0.approvedBy"]').fill('QA Lead');await p.locator('[data-approval-field="0.date"]').fill('2026-10-07');await p.locator('[data-approval-field="0.reference"]').fill('Buyer email 7 October');assert.equal(await p.evaluate(()=>app.planning.approvals.readiness(app.record).length),0);const image=await p.evaluate(()=>{const c=document.createElement('canvas');c.width=160;c.height=80;const ctx=c.getContext('2d');ctx.fillStyle='#076';ctx.fillRect(0,0,160,80);return Array.from(Uint8Array.from(atob(c.toDataURL('image/png').split(',')[1]),c=>c.charCodeAt(0)))});await p.locator('[data-approval-photo="0"]').setInputFiles({name:'proof.png',mimeType:'image/png',buffer:Buffer.from(image)});await p.waitForFunction(()=>!!app.record.approvals[0].photo);await p.locator('[data-approval-field="0.reference"]').fill('');assert.equal(await p.evaluate(()=>app.planning.approvals.readiness(app.record).length),0);await p.locator('[data-approval-field="0.reference"]').fill('Buyer email 7 October');await p.evaluate(()=>app.closeModal());this.pass('mobile approval form and compressed photo proof');
    await p.evaluate(()=>app.command('measure-check'));for(const [key,value]of Object.entries({pom:'Chest',spec:'50',actual:'51.5',tol:'1'}))await p.locator(`[data-compare-field="0.${key}"]`).fill(value);await p.locator('[data-compare-field="0.unit"]').selectOption('cm');await p.locator('[data-compare-field="0.checkRequired"]').check();assert.match(await p.locator('[data-measure-result="0"]').textContent(),/Outside tolerance/);assert.equal(await p.evaluate(()=>app.validation.readiness(app.record).controlsReady),false);await p.locator('[data-compare-field="0.actual"]').fill('51');assert.match(await p.locator('[data-measure-result="0"]').textContent(),/Within tolerance/);assert.equal(await p.evaluate(()=>app.validation.readiness(app.record).controlsReady),true);await p.evaluate(()=>app.closeModal());this.pass('mobile measurement form and required release gate');
    await p.evaluate(()=>app.command('changes'));await p.locator('#reviewerName').fill('QA Lead');await p.locator('[data-plan-action="review-point"]').click();await p.evaluate(()=>app.closeModal());await p.evaluate(()=>{app.record.signatures.factory={image:'old',name:'Old'};app.record.release.decision='GO'});await p.locator('.identity-field [data-bind="meta.style"]').fill('PLANNING-REVISED');assert.equal(await p.evaluate(()=>app.record.release.decision),'');assert.equal(await p.evaluate(()=>Object.keys(app.record.signatures).length),0);await p.evaluate(()=>app.command('changes'));assert.match(await p.locator('#modalBody').innerText(),/PLANNING-QA/);assert.match(await p.locator('#modalBody').innerText(),/PLANNING-REVISED/);await p.locator('#reviewerName').fill('QA Lead');await p.locator('[data-plan-action="review-point"]').click();assert.ok(await p.locator('#reviewAcknowledged').count());await p.locator('#reviewAcknowledged').check();await p.locator('[data-plan-action="review-point"]').click();assert.equal(await p.evaluate(()=>app.planning.changes.diff(app.record).length),0);await p.evaluate(()=>app.closeModal());this.pass('before/after form, explicit review and stale sign-off removal');
    await p.evaluate(()=>app.save(true));await p.reload();await p.locator('#homeScreen [data-command="continue"]').click();assert.equal(await p.evaluate(()=>app.record.approvals[0].approvedBy),'QA Lead');assert.equal(await p.evaluate(()=>app.record.measurements[0].actual),'51');assert.equal(await p.evaluate(()=>app.record.changeReview.history.length),2);const portable=await p.evaluate(()=>app.codec.encode(app.record));await p.locator('#importInput').setInputFiles({name:'planning.vesappm',mimeType:'application/json',buffer:Buffer.from(portable)});await p.waitForTimeout(400);assert.equal(await p.evaluate(()=>app.record.approvals[0].reference),'Buyer email 7 October');assert.ok(await p.evaluate(()=>app.record.approvals[0].photo.startsWith('data:image/jpeg;base64,')));assert.equal(await p.evaluate(()=>app.record.measurements[0].checkRequired),true);assert.equal(await p.evaluate(()=>app.record.changeReview.history.length),2);this.pass('autosave/reload and saved-copy roundtrip preserve all three controls');
    for(const language of ['bn','hi','ta']){await p.evaluate(l=>app.changeLanguage(l),language);await p.evaluate(()=>app.command('measure-check'));const text=await p.locator('[data-sentence="measurementHelp"]').textContent();assert.match(text,language==='bn'?/[\u0980-\u09ff]/:language==='hi'?/[\u0900-\u097f]/:/[\u0b80-\u0bff]/);assert.ok(await p.evaluate(()=>document.documentElement.scrollWidth<=innerWidth+1));await p.screenshot({path:`/tmp/ppm-planning-${language}.png`});await p.evaluate(()=>app.closeModal())}this.pass('three Indic guidance languages and mobile overflow');
    for(const mode of ['approvals','measurements','changes','full']){const result=await p.evaluate(async mode=>{const blob=await app.reports.pdf(app.record,mode);return {size:blob.size,bytes:Array.from(new Uint8Array(await blob.arrayBuffer()))}},mode);assert.ok(result.size>1000);fs.writeFileSync(`/tmp/ppm-${mode}.pdf`,Buffer.from(result.bytes))}this.pass('three new reports and integrated full PDF');
    await p.evaluate(()=>{app.record.locked=true;app.updateLock()});await p.evaluate(()=>app.command('approvals'));assert.equal(await p.locator('[data-approval-field="0.reference"]').isDisabled(),true);await p.evaluate(()=>app.closeModal());await p.evaluate(()=>app.command('measure-check'));assert.equal(await p.locator('[data-compare-field="0.actual"]').isDisabled(),true);await p.evaluate(()=>app.closeModal());this.pass('finalized forms stay read-only');
    const clearSafe=await p.evaluate(async()=>{const c=document.createElement('canvas');c.style.cssText='width:100px;height:50px';document.body.append(c);const source=document.createElement('canvas');source.width=50;source.height=25;source.getContext('2d').fillRect(0,0,50,25);const pad=new SignaturePad(c,()=>{});pad.restore(source.toDataURL());pad.clear();await new Promise(r=>setTimeout(r,40));const empty=[...pad.ctx.getImageData(0,0,c.width,c.height).data].every(v=>v===0);pad.dispose();c.remove();return empty});assert.equal(clearSafe,true);this.pass('delayed restore cannot repaint a cleared signature');
    await p.evaluate(()=>navigator.serviceWorker.ready);await p.waitForFunction(()=>!!navigator.serviceWorker.controller);await this.context.setOffline(true);await p.reload();await p.waitForFunction(()=>typeof app!=='undefined');assert.equal(await p.evaluate(()=>APP_VERSION),'5.1.0');await this.context.setOffline(false);assert.deepEqual(this.errors,[]);this.pass('new services cached offline and no uncaught errors');console.log('TOTAL',this.passes.length)
  }
  async stop(){await this.browser?.close();if(this.server)await new Promise(r=>this.server.close(r))}
}
const test=new PlanningRegression();test.run().catch(e=>{console.error(e);process.exitCode=1}).finally(()=>test.stop());
