/** Executable browser regression for PPM persistence, security and user workflows.
 * Access: NODE_PATH=<runtime node_modules> CHROMIUM_PATH=<binary> node tests/regression.cjs
 * Owns an ephemeral local HTTP server and browser profile; never touches production data.
 * Fail-fast assertions report nonzero exit status. Artifacts go to TEST_OUTPUT or /tmp/ppm-qa. */
const fs=require('fs'),path=require('path'),http=require('http'),assert=require('assert/strict');
const {chromium}=require('playwright');
class PpmRegression {
  constructor(){this.root=path.resolve(__dirname,'../../..');this.out=process.env.TEST_OUTPUT||'/tmp/ppm-qa';this.errors=[];this.passes=[]}
  /** Serve repository assets under their deployed paths with browser-correct MIME types. */
  async start(){fs.mkdirSync(this.out,{recursive:true});this.server=http.createServer((req,res)=>{let file=path.join(this.root,decodeURIComponent(new URL(req.url,'http://test').pathname));if(!file.startsWith(this.root+path.sep)){res.writeHead(403).end();return}try{if(fs.statSync(file).isDirectory())file=path.join(file,'index.html');const types={'.js':'application/javascript','.css':'text/css','.html':'text/html','.webmanifest':'application/manifest+json','.ttf':'font/ttf','.png':'image/png'};res.setHeader('Content-Type',types[path.extname(file)]||'application/octet-stream');res.end(fs.readFileSync(file))}catch{res.writeHead(404).end()}});await new Promise(r=>this.server.listen(0,'127.0.0.1',r));this.url=`http://127.0.0.1:${this.server.address().port}/apps/ppm/`;this.browser=await chromium.launch({headless:true,...(process.env.CHROMIUM_PATH?{executablePath:process.env.CHROMIUM_PATH}:{}),args:['--no-sandbox','--disable-gpu','--disable-dev-shm-usage']});this.context=await this.browser.newContext({viewport:{width:1440,height:1000}});await this.context.addInitScript(()=>localStorage.setItem('vesa.appcentre.session.v1',JSON.stringify({email:'qa@vesaent.com',name:'QA User',role:'admin',userKey:'qa-vesaent-com',loginAt:'2026-10-09T00:00:00.000Z',expiresAt:'2099-01-01T00:00:00.000Z'})));this.page=await this.context.newPage();this.page.on('pageerror',e=>{this.errors.push(e.message);console.log('BROWSER ERROR',e.message)});await this.page.goto(this.url);await this.page.waitForFunction(()=>typeof app!=='undefined'&&document.body.classList.contains('at-home'))}
  pass(name){this.passes.push(name);console.log('PASS',name)}
  async run(){await this.start();const p=this.page;
    assert.equal(await p.evaluate(async()=>(await app.repo.list()).length),0);this.pass('startup home creates no phantom draft');await p.screenshot({path:path.join(this.out,'home.png')});
    await p.locator('#homeScreen [data-command="new"]').click();await p.locator('#quickStyle').fill('QA-STYLE-001');await p.locator('#quickFactory').fill('QA Factory');await p.locator('#quickBuyer').fill('QA Buyer');await p.locator('#garmentProfileSelect').selectOption('tshirt');await p.waitForTimeout(650);assert.equal(await p.evaluate(async()=>(await app.repo.get(app.record.id)).meta.style),'QA-STYLE-001');this.id=await p.evaluate(()=>app.record.id);await p.reload();await p.getByRole('button',{name:/Continue Last PPM/}).click();assert.equal(await p.locator('#quickStyle').inputValue(),'QA-STYLE-001');this.pass('autosave and reload restore');
    const coverage=await p.evaluate(()=>app.coverage.compute(app.record).applicable);for(const lang of ['bn','hi','ta','en']){await p.locator('#fileMenu .language-select').selectOption(lang);assert.equal(await p.locator('#quickStyle').inputValue(),'QA-STYLE-001');const misses=await p.evaluate(lang=>SECTION_SCHEMA.flatMap(s=>s.items).filter(i=>lang!=='en'&&!PPM_SENTENCES[i[0]]?.[lang]).map(i=>i[0]),lang);assert.deepEqual(misses,[]);const text=await p.locator('.checkpoint[data-id="O01"] .cp-title').textContent();if(lang==='bn')assert.match(text,/[\u0980-\u09ff]/);if(lang==='hi')assert.match(text,/[\u0900-\u097f]/);if(lang==='ta')assert.match(text,/[\u0b80-\u0bff]/)}this.pass('all master checkpoint translations and data preservation');
    await p.locator('[data-custom-add="order"]').click();await p.locator('#customLabel').fill('Check customer-specific seam finish.');await p.locator('#customCritical').check();await p.locator('#saveCustom').click();assert.equal(await p.evaluate(()=>app.coverage.compute(app.record).applicable),coverage+1);const custom=await p.evaluate(()=>app.record.customCheckpoints[0].id);await p.locator(`[data-id="${custom}"] [data-status="ACTION"]`).click();assert.equal(await p.evaluate(()=>app.record.actions.length),1);await p.evaluate(()=>app.undo(-1));assert.equal(await p.evaluate(()=>app.record.actions.length),0);await p.evaluate(()=>app.undo(1));assert.equal(await p.evaluate(()=>app.record.actions.length),1);this.pass('custom checkpoint coverage/action integration and undo/redo');
    await p.evaluate(()=>{app.record.release.decision='HOLD';app.toggleFinalize()});await p.locator('#confirmYes').click();await p.waitForTimeout(500);await p.evaluate(()=>app.closeModal());assert.equal(await p.evaluate(async()=>(await app.repo.get(app.record.id)).locked),true);assert.equal(await p.locator('#quickStyle').isDisabled(),true);this.pass('finalization persisted and quick header locked');
    const beforeDemo=await p.evaluate(async()=>(await app.repo.list()).length);await p.evaluate(()=>app.loadDemo());await p.evaluate(()=>app.save());assert.equal(await p.evaluate(async()=>(await app.repo.list()).length),beforeDemo);await p.locator('#quickStyle').fill('DEMO CHANGED');await p.waitForTimeout(500);assert.equal(await p.evaluate(async()=>(await app.repo.list()).length),beforeDemo);await p.evaluate(()=>app.profileCopy());assert.equal(await p.evaluate(()=>app.record.meta.profile),'tshirt');assert.equal(await p.locator('#quickStyle').inputValue(),'');assert.equal(await p.evaluate(()=>Object.values(app.record.statuses).filter(Boolean).length),0);this.pass('demo isolation and clean profile-only copy');
    const invalid=await p.evaluate(()=>{const r=PpmRecordFactory.create();const cases=[{...r,id:'"><img src=x onerror=alert(1)>'},{...r,statuses:{...r.statuses,O01:'BAD'}},{...r,photos:{style:'javascript:alert(1)',evidence:{}}},{...r,photos:{style:'data:image/svg+xml;base64,PHN2Zz4=',evidence:{}}},{...r,meta:{...r.meta,processes:'print'}},{format:'VESA-PPM',schema:999,record:r}];return cases.map(c=>{try{app.codec.decode(c);return false}catch{return true}})});assert.ok(invalid.every(Boolean));this.pass('malicious IDs, statuses, images, schema and structure rejected');
    const legacy=await p.evaluate(()=>{const r=new DemoDataBuilder(app.relevance).build();r.version='4.1.1';return JSON.stringify(r)});await p.locator('#importInput').setInputFiles({name:'legacy.json',mimeType:'application/json',buffer:Buffer.from(legacy)});await p.waitForTimeout(500);assert.equal(await p.locator('#quickStyle').inputValue(),'TS-DEMO-001');this.pass('V4 JSON import migration');
    const currentId=await p.evaluate(()=>app.record.id);await p.locator('#importInput').setInputFiles({name:'bad.json',mimeType:'application/json',buffer:Buffer.from('{bad')});assert.equal(await p.evaluate(()=>app.record.id),currentId);this.pass('invalid backup leaves active record intact');
    await p.evaluate(()=>app.save(true));assert.ok(await p.evaluate(async()=>(await app.recovery.list(app.record.id)).length>0));this.pass('durable recovery snapshot');
    await p.evaluate(()=>app.confirmResetSection('order'));await p.locator('#confirmYes').click();await p.waitForFunction(()=>app.record.statuses.O01==='');await p.evaluate(()=>app.undo(-1));assert.equal(await p.evaluate(()=>app.record.statuses.O01),'OK');this.pass('section reset snapshot and undo restore');
    const portable=await p.evaluate(()=>{const canvas=document.createElement('canvas');canvas.width=120;canvas.height=60;const ctx=canvas.getContext('2d');ctx.fillStyle='#123';ctx.fillRect(5,10,90,2);const r=U.clone(app.record);r.photos.style=canvas.toDataURL('image/png');r.photos.evidence.ppSample=r.photos.style;r.signatures.factory={image:r.photos.style,name:'QA Authorized',designation:'QA',date:U.today(),time:'09:00'};return app.codec.encode(r)});await p.locator('#importInput').setInputFiles({name:'roundtrip.vesappm',mimeType:'application/json',buffer:Buffer.from(portable)});await p.waitForTimeout(350);assert.ok(await p.evaluate(()=>!!app.record.signatures.factory?.image&&!!app.record.photos.evidence.ppSample));this.pass('portable backup preserves image, evidence and named signature');
    await p.locator('#fileMenu .language-select').selectOption('bn');await p.screenshot({path:path.join(this.out,'editor-bengali.png')});
    for(const mode of (process.env.QUICK_QA?['actions']:['summary','actions','evidence','checklist','full'])){const out=await p.evaluate(async mode=>{const blob=await app.reports.pdf(app.record,mode);return {bytes:Array.from(new Uint8Array(await blob.arrayBuffer())),pages:app.reports.pages.length}},mode);assert.ok(out.pages>0);assert.ok(out.bytes.length>1000);fs.writeFileSync(path.join(this.out,`${mode}-bn.pdf`),Buffer.from(out.bytes));if(mode==='full')console.log('Full report pages',out.pages)}this.pass(process.env.QUICK_QA?'Bengali action PDF generation':'all PDF modes with Bengali fonts');
    for(const language of ['hi','ta']){await p.evaluate(language=>app.changeLanguage(language),language);const bytes=await p.evaluate(async()=>Array.from(new Uint8Array(await (await app.reports.pdf(app.record,'actions')).arrayBuffer())));fs.writeFileSync(path.join(this.out,`actions-${language}.pdf`),Buffer.from(bytes))}this.pass('Hindi and Tamil PDF generation');await p.evaluate(()=>app.changeLanguage('bn'));
    await p.evaluate(()=>app.exportMenu());await p.locator('#reportMode').selectOption('actions');await p.locator('#makePdf').click();await p.locator('#downloadPdf').waitFor();const download=p.waitForEvent('download');await p.locator('#downloadPdf').click();assert.ok((await download).suggestedFilename().endsWith('.pdf'));await p.evaluate(()=>app.closeModal());this.pass('PDF export UI generates a downloadable file');
    const csv=await p.evaluate(async()=>{const r=U.clone(app.record);r.actions[0].owner='=HYPERLINK("bad")';return app.reports.csv(r).text()});assert.ok(csv.includes("'=HYPERLINK"));this.pass('CSV formula injection neutralized');
    const second=await this.context.newPage();await second.goto(this.url);await second.waitForFunction(()=>document.body.classList.contains('at-home'));await second.evaluate(()=>app.showEditor());await p.locator('#quickStyle').fill('TAB ONE');await p.evaluate(()=>app.save(true));await second.locator('#quickStyle').fill('TAB TWO');assert.equal(await second.evaluate(()=>app.save(true)),false);assert.equal(await p.evaluate(async()=>(await app.repo.get(app.record.id)).meta.style),'TAB ONE');await second.close();this.pass('cross-tab overwrite rejected');
    const failed=await p.evaluate(async()=>{const id=app.record.id,save=app.repo.save;app.repo.save=async()=>{throw Error('Quota exceeded')};await app.newRecord();app.repo.save=save;return app.record.id===id});assert.equal(failed,true);this.pass('save failure blocks record transition');
    await p.setViewportSize({width:390,height:844});await p.screenshot({path:path.join(this.out,'mobile-bengali.png')});assert.ok(await p.evaluate(()=>document.documentElement.scrollWidth<=innerWidth+1));this.pass('390px mobile no horizontal page overflow');
    await p.evaluate(()=>navigator.serviceWorker.ready);await p.waitForTimeout(300);await this.context.setOffline(true);await p.reload();await p.waitForFunction(()=>document.body.classList.contains('at-home'));assert.equal(await p.evaluate(()=>APP_VERSION),'5.1.3');await this.context.setOffline(false);this.pass('offline reload includes full app bundle');
    assert.deepEqual(this.errors,[]);this.pass('no uncaught browser errors');fs.writeFileSync(path.join(this.out,'results.json'),JSON.stringify({passed:this.passes,errors:this.errors},null,2));
  }
  async stop(){await this.browser?.close();await new Promise(r=>this.server?this.server.close(r):r())}
}
const run=new PpmRegression();run.run().catch(e=>{console.error(e);process.exitCode=1}).finally(()=>run.stop());
