/** Real 5.0.1 -> current worker lifecycle regression. Runs a disposable local
 * server/browser with synthetic meetings; optional PRIVATE_COPY stays local.
 * Owns install failures, concurrent legacy tabs, explicit reload and offline proof. */
const fs=require('fs'),path=require('path'),http=require('http'),assert=require('assert/strict'),{execFileSync}=require('child_process');
const {chromium}=require('playwright');
class UpdateRegression {
  constructor(){this.root=path.resolve(__dirname,'../../..');this.release='old';this.oldFiles=new Map();this.errors=[]}
  bytes(file){if(this.release==='old'&&file.startsWith('apps/ppm/')){if(!this.oldFiles.has(file))this.oldFiles.set(file,execFileSync('git',['show','16b6e45:'+file],{cwd:this.root,maxBuffer:20*1024*1024}));return this.oldFiles.get(file)}const bytes=fs.readFileSync(path.join(this.root,file));return this.release==='future'&&/\.(js|html|css)$/.test(file)?Buffer.from(bytes.toString().replaceAll('5.1.1','5.1.2')):bytes}
  async start(){this.server=http.createServer((req,res)=>{let file=decodeURIComponent(new URL(req.url,'http://localhost').pathname).slice(1);if(file.endsWith('/'))file+='index.html';try{if(this.release==='broken'&&file.endsWith('planning-panel.js'))return res.writeHead(503).end();const type={'.html':'text/html','.js':'application/javascript','.css':'text/css','.ttf':'font/ttf','.png':'image/png'}[path.extname(file)]||'application/octet-stream';res.writeHead(200,{'Content-Type':type,'Cache-Control':'no-store'}).end(this.bytes(file))}catch{res.writeHead(404).end()}});await new Promise(r=>this.server.listen(0,'127.0.0.1',r));this.url=`http://127.0.0.1:${this.server.address().port}/apps/ppm/`;this.browser=await chromium.launch({executablePath:process.env.CHROMIUM_PATH,headless:true,args:['--no-sandbox']});this.context=await this.browser.newContext({viewport:{width:390,height:844}});this.page=await this.context.newPage();this.page.on('pageerror',e=>this.errors.push(e.message));await this.page.goto(this.url);await this.page.waitForFunction(()=>typeof app!=='undefined'&&!!navigator.serviceWorker.controller)}
  async run(){await this.start();const p=this.page;assert.equal(await p.evaluate(()=>APP_VERSION),'5.0.1');await p.evaluate(async()=>{await app.newRecord();app.record.meta.style='KEEP-SAVED';await app.save(true);app.record.meta.style='KEEP-UNSAVED'});const other=await this.context.newPage();await other.goto(this.url);await other.waitForFunction(()=>typeof app!=='undefined');
    this.release='broken';await p.evaluate(async()=>{const r=await navigator.serviceWorker.getRegistration();await r.update();await new Promise(resolve=>{const w=r.installing;if(!w)return resolve();w.addEventListener('statechange',()=>{if(w.state==='redundant')resolve()})})});assert.equal(await p.evaluate(()=>APP_VERSION),'5.0.1');assert.equal(await p.evaluate(()=>app.record.meta.style),'KEEP-UNSAVED');console.log('PASS incomplete installation leaves old worker and unsaved work intact');
    this.release='new';await p.evaluate(async()=>{window.workerChanged=false;navigator.serviceWorker.addEventListener('controllerchange',()=>window.workerChanged=true);await(await navigator.serviceWorker.getRegistration()).update()});await p.waitForFunction(()=>window.workerChanged);assert.equal(await p.evaluate(()=>APP_VERSION),'5.0.1');assert.equal(await p.evaluate(()=>app.record.meta.style),'KEEP-UNSAVED');assert.equal(await other.evaluate(()=>APP_VERSION),'5.0.1');assert.equal(await p.evaluate(async()=>{const r=await fetch('./core.js?v=5.0.1');return (await r.text()).includes("APP_VERSION='5.0.1'")}),true);await p.evaluate(()=>app.save(true));console.log('PASS old windows stay open and exact old assets remain available');
    await p.reload();await p.waitForFunction(()=>typeof app!=='undefined'&&APP_VERSION==='5.1.1');assert.equal(await p.evaluate(()=>app.record.meta.style),'KEEP-UNSAVED');await p.evaluate(()=>app.newRecord());const portable=await p.evaluate(()=>{app.record.meta.style='SCHEMA-TWO';return app.codec.encode(app.record)});assert.equal(await other.evaluate(raw=>{try{app.codec.decode(JSON.parse(raw));return false}catch{return true}},portable),true);await p.locator('#importInput').setInputFiles({name:'copy.vesappm',mimeType:'application/json',buffer:Buffer.from(portable)});await p.waitForFunction(()=>app.record.meta.style==='SCHEMA-TWO');console.log('PASS newer saved copy rejected by legacy reader opens after upgrade');
    if(process.env.PRIVATE_COPY){await p.locator('#importInput').setInputFiles(process.env.PRIVATE_COPY);await p.waitForFunction(()=>app.record.meta.style!=='SCHEMA-TWO');assert.equal(await p.evaluate(()=>app.record.version),'5.1.1');console.log('PASS supplied private saved copy validated and opened locally')}
    await p.evaluate(async()=>{window.previous=app.record.id;await app.save(true)});await this.context.setOffline(true);await p.reload();await p.waitForFunction(()=>typeof app!=='undefined');assert.equal(await p.evaluate(()=>APP_VERSION),'5.1.1');assert.ok(await p.evaluate(()=>app.record.id.startsWith('PPM-')));await this.context.setOffline(false);console.log('PASS complete new bundle and meetings reopen offline');
    await p.evaluate(async()=>{window.savedWorker=app.worker;window.savedVersion=app.workerVersion;window.savedSave=app.save;window.savedCheck=app.checkForUpdate;app.worker={update:async()=>{}};app.workerVersion=async()=>'next';app.production=true;app.training=false;app.save=async()=>false;await app.checkForUpdate()});assert.equal(await p.evaluate(()=>typeof window.savedCheck),'function');console.log('PASS failed save blocks requested update reload');
    await p.evaluate(async()=>{app.save=async()=>{app.record.meta.style='EDIT-DURING-SAVE';return true};await app.checkForUpdate()});assert.equal(await p.evaluate(()=>app.record.meta.style),'EDIT-DURING-SAVE');assert.equal(await p.evaluate(()=>typeof window.savedCheck),'function');console.log('PASS edits during save block reload');
    await p.evaluate(()=>{app.worker=window.savedWorker;app.workerVersion=window.savedVersion;app.save=window.savedSave;app.record.meta.style='SAVE-BEFORE-UPDATE'});this.release='future';await p.evaluate(()=>app.worker.update());await p.locator('#ppmApplyUpdate').waitFor();assert.equal(await p.evaluate(()=>APP_VERSION),'5.1.1');await p.locator('#ppmApplyUpdate').click();await p.waitForFunction(()=>typeof app!=='undefined'&&APP_VERSION==='5.1.2');assert.equal(await p.evaluate(()=>app.record.meta.style),'SAVE-BEFORE-UPDATE');assert.ok(await p.evaluate(()=>document.documentElement.scrollWidth<=innerWidth+1));console.log('PASS persistent offer and explicit Save & Update preserve latest meeting');assert.deepEqual(this.errors,[])

  }
  async stop(){await this.browser?.close();if(this.server)await new Promise(r=>this.server.close(r))}
}
const test=new UpdateRegression();test.run().catch(e=>{console.error(e);process.exitCode=1}).finally(()=>test.stop());
