'use strict';
/** Meeting-controls UI owner. Constructed once by V5Workspace with PlanningService.
 * Owns one summary section and modal event lifetimes; mutations always go through
 * workspace history/autosave. Imported text is escaped. Photo reads stay on device,
 * check record identity after await, and never mutate finalized/removed records. */
class MeetingControls {
  constructor(workspace,planning){this.workspace=workspace;this.planning=planning;this.abort=null;this.view=''}
  /** Dispose handlers whenever the shared modal is replaced/closed. No owned record state. */
  dispose(){this.abort?.abort();this.abort=null;this.view=''}
  /** Mount the single summary before the master checklist; repeated calls are idempotent. */
  mount(){if(document.getElementById('meetingControls'))return;const section=document.createElement('section');section.id='meetingControls';section.className='section-card';document.getElementById('sectionsRoot').before(section);this.update()}
  sentence(key){return this.workspace.locale.sentence(key,key)}
  /** Refresh read-only counts from the active record; does not touch forms or persist. */
  update(){const root=document.getElementById('meetingControls');if(!root)return;const r=this.workspace.record,p=this.planning.readiness(r),required=r.approvals.filter(a=>a.required).length,checked=r.measurements.filter(m=>m.checkRequired).length;root.innerHTML=`<div class="section-head"><h2>MEETING CHECKS</h2></div><div class="planning-summary"><button class="planning-card" data-command="approvals"><b>Approvals</b><span>${required-p.approvals.length}/${required} required complete</span></button><button class="planning-card" data-command="measure-check"><b>Measurement Check</b><span>${checked-p.measurements.length}/${checked} required within tolerance</span></button><button class="planning-card" data-command="changes"><b>What Changed?</b><span>${r.changeReview.baseline?p.changes.length+' changes to review':'Save a starting point'}</span></button></div>`}
  open(view){if(view==='approvals')this.approvals();else if(view==='measure-check')this.measurements();else this.changes()}
  input(name,label,value,type='text',extra=''){return `<label>${label}<input type="${type}" ${name} value="${U.esc(value||'')}" ${extra}></label>`}
  /** Bind only this modal's controls. Finite field keys protect the domain boundary. */
  bind(view){this.abort=new AbortController();this.view=view;const body=document.getElementById('modalBody'),options={signal:this.abort.signal};body.addEventListener('input',e=>this.edit(e.target),options);body.addEventListener('change',e=>{if(e.target.type==='file')this.photo(e.target).catch(()=>this.workspace.toast('This photo could not be opened. Try a smaller photo.'));else this.edit(e.target)},options);body.addEventListener('click',e=>{const b=e.target.closest('[data-plan-action]');if(!b)return;const w=this.workspace,r=w.record;if(r.locked)return;switch(b.dataset.planAction){case'add-approval':if(r.approvals.length>=30){w.toast('Maximum 30 approvals per meeting.');return}r.approvals.push(ApprovalRegister.create(document.getElementById('newApprovalLabel').value.trim()));w.mutate(false);this.approvals();break;case'remove-approval':{const a=r.approvals[Number(b.dataset.index)];if(!a)return;w.openConfirm('Remove this approval?','This removes the approval from this meeting.',()=>{r.approvals=r.approvals.filter(x=>x.id!==a.id);w.mutate(false);this.approvals()});break}case'remove-photo':{const a=r.approvals[Number(b.dataset.index)];a.photo='';a.photoRevision=crypto.randomUUID();w.mutate(false);this.approvals();break}case'add-measure':if(r.measurements.length>=100){w.toast('Maximum 100 measurement rows.');return}r.measurements.push(PpmRecordFactory.measurement());w.renderMeasurements();w.mutate(false);this.measurements();break;case'review-point':this.review();break}},options)}
  /** Copy one whitelisted input into the active unlocked record and queue history/save. */
  edit(el){const w=this.workspace,r=w.record;if(r.locked)return;let changed=false;if(el.dataset.approvalField){const [index,key]=el.dataset.approvalField.split('.'),a=r.approvals[Number(index)];if(!a||!['label','required','status','approvedBy','date','reference','notes'].includes(key))return;a[key]=el.type==='checkbox'?el.checked:el.value;changed=true;this.approvalResult(Number(index))}if(el.dataset.compareField){const [index,key]=el.dataset.compareField.split('.'),m=r.measurements[Number(index)];if(!m||!['pom','spec','tol','actual','unit','tolMinus','tolPlus','checkRequired'].includes(key))return;m[key]=el.type==='checkbox'?el.checked:el.value;changed=true;this.measurementResult(Number(index));const peer=document.querySelector(`[data-measure="${index}.${key}"]`);if(peer)peer.value=m[key]}if(changed)w.mutate(false)}
  /** Async proof photos preserve active-record and row identity across await. */
  async photo(input){const w=this.workspace,r=w.record,a=r.approvals[Number(input.dataset.approvalPhoto)],file=input.files?.[0];if(!a||!file||r.locked)return;const id=r.id,approvalId=a.id,image=await w.images.compress(file,1200,.72);if(w.record.id!==id||w.record.locked)return;const target=w.record.approvals.find(x=>x.id===approvalId);if(!target)return;target.photo=image;target.photoRevision=crypto.randomUUID();w.mutate(false);if(this.view==='approvals')this.approvals()}
  /** Open escaped approval cards; only explicit required rows constrain release. */
  approvals(){const w=this.workspace,r=w.record,disabled=r.locked?'disabled':'';w.openModal('Approvals',`<p data-sentence="approvalHelp">Add only approvals your buyer requires. Required approvals need a name, date and approval reference or proof photo before release.</p><div class="planning-add"><label>Approval name<input id="newApprovalLabel" list="approvalNames" maxlength="200" ${disabled}></label><datalist id="approvalNames">${ApprovalRegister.labels.map(x=>`<option value="${x}"></option>`).join('')}</datalist><button class="primary-btn" data-plan-action="add-approval" ${disabled}>ADD APPROVAL</button></div><div class="planning-list">${r.approvals.map((a,i)=>`<article class="planning-item"><h3>${U.esc(a.label||'Approval '+(i+1))}</h3><div class="planning-fields">${this.input(`data-approval-field="${i}.label"`,'Approval name',a.label,'text',`maxlength="200" ${disabled}`)}<label>Status<select data-approval-field="${i}.status" ${disabled}>${['Pending','Approved','Rejected','Not needed'].map(x=>`<option ${a.status===x?'selected':''}>${x}</option>`).join('')}</select></label>${this.input(`data-approval-field="${i}.approvedBy"`,'Approved by',a.approvedBy,'text',`maxlength="200" list="participantNames" ${disabled}`)}${this.input(`data-approval-field="${i}.date"`,'Approval date',a.date,'date',disabled)}${this.input(`data-approval-field="${i}.reference"`,'Approval reference',a.reference,'text',`maxlength="1000" placeholder="Email date, approved sample or document reference" ${disabled}`)}<label class="planning-check"><input type="checkbox" data-approval-field="${i}.required" ${a.required?'checked':''} ${disabled}> Required before release</label></div><label>Notes / reason not needed<textarea data-approval-field="${i}.notes" maxlength="2000" ${disabled}>${U.esc(a.notes)}</textarea></label><p data-approval-result="${i}" class="planning-result" data-live-result></p>${a.photo?`<img class="approval-proof" src="${U.esc(a.photo)}" alt="Approval proof"><button class="soft-btn" data-plan-action="remove-photo" data-index="${i}" ${disabled}>REMOVE PHOTO</button>`:''}<label>Proof photo<input type="file" accept="image/jpeg,image/png,image/webp" data-approval-photo="${i}" ${disabled}></label><button class="danger-btn" data-plan-action="remove-approval" data-index="${i}" ${disabled}>REMOVE APPROVAL</button></article>`).join('')||'<p>No approvals added yet.</p>'}</div>`);this.bind('approvals');r.approvals.forEach((_,i)=>this.approvalResult(i))}
  /** Update a live approval result without replacing focused inputs or translating data. */
  approvalResult(i){const a=this.workspace.record.approvals[i],el=document.querySelector(`[data-approval-result="${i}"]`);if(!a||!el)return;const gap=this.planning.approvals.gap(a);el.textContent=this.sentence(a.required?(gap||'Required approval complete.'):'Optional approval.');el.classList.toggle('needs-attention',!!gap)}
  /** Open comparison forms linked to existing POM rows; preserve legacy spec strings. */
  measurements(){const w=this.workspace,r=w.record,disabled=r.locked?'disabled':'';w.openModal('Measurement Check',`<p data-sentence="measurementHelp">Use the buyer's spec and tolerance. Enter all numbers in the selected unit. Leave both allowed-below/above boxes blank to use the single tolerance. No tolerance is assumed.</p><div class="planning-list">${r.measurements.map((m,i)=>`<article class="planning-item"><h3>Measurement ${i+1}</h3><div class="planning-fields">${this.input(`data-compare-field="${i}.pom"`,'Point of measure',m.pom,'text',`maxlength="500" ${disabled}`)}<label>Unit<select data-compare-field="${i}.unit" ${disabled}>${[['','Choose unit'],['cm','cm'],['in','inches']].map(([k,v])=>`<option value="${k}" ${m.unit===k?'selected':''}>${v}</option>`).join('')}</select></label>${[['spec','Buyer spec'],['actual','Sample actual'],['tol','Tolerance (±)'],['tolMinus','Allowed below (optional)'],['tolPlus','Allowed above (optional)']].map(([k,l])=>this.input(`data-compare-field="${i}.${k}"`,l,m[k],'text',`inputmode="decimal" maxlength="500" ${disabled}`)).join('')}<label class="planning-check"><input type="checkbox" data-compare-field="${i}.checkRequired" ${m.checkRequired?'checked':''} ${disabled}> Required before release</label></div><p data-measure-result="${i}" class="planning-result" data-live-result aria-live="polite"></p></article>`).join('')}</div><button class="soft-btn" data-plan-action="add-measure" ${disabled}>ADD MEASUREMENT</button>`);this.bind('measure-check');r.measurements.forEach((_,i)=>this.measurementResult(i))}
  /** Render the domain result in the sentence language; bounds remain numeric and explicit. */
  measurementResult(i){const m=this.workspace.record.measurements[i],el=document.querySelector(`[data-measure-result="${i}"]`);if(!m||!el)return;const result=this.planning.measurements.compare(m);el.textContent=this.sentence(result.status)+(result.difference===null?'':` · Difference ${this.planning.measurements.display(result.difference)} ${m.unit==='in'?'inches':m.unit} · Allowed ${this.planning.measurements.display(result.low)} to ${this.planning.measurements.display(result.high)}`);el.classList.toggle('needs-attention',result.status==='Outside tolerance'||result.status==='Check entries');if(result.status==='Check entries')el.textContent+=' · '+this.sentence('Choose a unit and enter valid numbers for the spec, actual and tolerance.')}
  /** Show bounded differences/history and obtain named acknowledgement before advancing. */
  changes(){const w=this.workspace,r=w.record,diff=this.planning.changes.diff(r),base=r.changeReview.baseline,disabled=r.locked?'disabled':'';const sections=[...new Set(diff.flatMap(d=>d.sections))].map(id=>SECTION_SCHEMA.find(s=>s.id===id)?.title).filter(Boolean);w.openModal('What Changed?',`<p data-sentence="changesHelp">Save a starting point after reviewing the meeting. Later changes show the old and new values. Review the affected sections before recording a fresh release and signatures.</p>${base?`<p>Last review: ${U.esc(new Date(base.at).toLocaleString())} · ${U.esc(base.reviewer)}</p>`:'<p>No starting point saved yet.</p>'}<p>${diff.length} changes to review</p>${sections.length?`<p>Review these sections: ${U.esc(sections.join(' / '))}</p>`:''}<div class="planning-list">${diff.slice(0,100).map(d=>`<article class="planning-item"><h3>${U.esc(d.label)}</h3><div class="change-values"><div><b>Before</b><p data-entered-text>${U.esc(d.before||'—')}</p></div><div><b>Now</b><p data-entered-text>${U.esc(d.after||'—')}</p></div></div></article>`).join('')}</div>${diff.length>100?'<p>Showing the first 100 changes. The saved review point includes all controlled values.</p>':''}<div class="planning-fields">${this.input('id="reviewerName"','Reviewed by','','text',`maxlength="200" list="participantNames" ${disabled}`)}${this.input('id="reviewNote"','Review note','','text',`maxlength="1000" ${disabled}`)}</div>${diff.length?`<label class="planning-check"><input id="reviewAcknowledged" type="checkbox" ${disabled}> I reviewed the affected sections and approval requirements.</label>`:''}<button class="primary-btn" data-plan-action="review-point" ${disabled}>${base?'SAVE REVIEWED POINT':'SAVE STARTING POINT'}</button><h3>Earlier reviews</h3>${r.changeReview.history.slice().reverse().map(h=>`<details class="review-history"><summary>${U.esc(new Date(h.at).toLocaleString())} · ${U.esc(h.reviewer)} · ${h.count} changes</summary><p data-entered-text>${U.esc(h.note||'No note')}</p>${h.changes.map(d=>`<p data-entered-text><b>${U.esc(d.label)}</b><br>${U.esc(d.before||'—')} → ${U.esc(d.after||'—')}</p>`).join('')}${h.count>h.changes.length?'<p>First 30 changes shown; total change count is recorded.</p>':''}</details>`).join('')||'<p>No earlier reviews yet.</p>'}`);this.bind('changes')}
  /** Named explicit review advances the point, never creates a production approval. */
  review(){const w=this.workspace,r=w.record;if(r.locked)return;const name=document.getElementById('reviewerName').value.trim(),note=document.getElementById('reviewNote').value.trim();if(!name){w.toast('Enter the name of the person who reviewed this meeting.');return}if(this.planning.changes.diff(r).length&&!document.getElementById('reviewAcknowledged')?.checked){w.toast('Review the affected sections and confirm before saving this point.');return}this.planning.changes.review(r,name,note);w.mutate(false);this.changes();w.toast('Reviewed point saved. Release and signatures still need approval.')}
}
