'use strict';
/** Offline report export. ReportService takes a record snapshot and domain/locale services.
 * Owns transient high-resolution canvases and PDF bytes, never record persistence.
 * Native canvas text shaping preserves Bengali/Hindi/Tamil; the resulting PDF is raster,
 * not searchable text. All pages paginate before drawing; long notes split safely.
 * PDF-lib is bundled locally. Errors leave the editor and original record intact. */
class ReportService {
  constructor(relevance,coverage,locale){this.relevance=relevance;this.coverage=coverage;this.locale=locale;this.pages=[];this.y=0;this.ctx=null;this.record=null}
  /** Wait for local Indic fonts so exports never substitute missing glyph boxes. */
  async fonts(){await Promise.all(['Bengali','Devanagari','Tamil'].map(f=>document.fonts.load(`16px ${f}`)));await document.fonts.ready}
  font(size=15,bold=false){this.ctx.font=`${bold?'700':'400'} ${size}px Arial, Bengali, Devanagari, Tamil, sans-serif`;this.ctx.textBaseline='top'}
  /** Start a landscape page with bounded content area and repeated identity. */
  page(title){const canvas=document.createElement('canvas');canvas.width=2244;canvas.height=1587;const c=canvas.getContext('2d');c.scale(2,2);this.ctx=c;this.pages.push(canvas);c.fillStyle='#fff';c.fillRect(0,0,1122,794);c.fillStyle='#0a2746';c.fillRect(0,0,1122,76);this.font(23,true);c.fillStyle='#fff';c.fillText('VESA Enterprise Inc. · PPM 360',34,19);this.font(12);c.fillText(`V${APP_VERSION} · ${this.record.locked?'FINALIZED':'DRAFT'}${this.record.training?' · DEMO / TRAINING ONLY':''}`,35,51);c.fillStyle='#c8a33a';c.fillRect(0,76,1122,3);this.font(16,true);c.fillStyle='#0a2746';c.fillText(title,34,94);this.font(11);c.fillStyle='#5e7080';const id=`${(this.record.meta.style||'Untitled style').slice(0,60)} · ${(this.record.meta.po||'No PO').slice(0,50)} · ${this.record.id}`;c.fillText(id,34,120);this.y=147;this.title=title}
  /** Wrap by measured glyph width; unusually long tokens split at grapheme boundaries. */
  lines(text,width){const result=[];for(const para of String(text||'—').split('\n')){let line='';for(const word of para.split(/\s+/)){if(this.ctx.measureText(line+(line?' ':'')+word).width<=width){line+=(line?' ':'')+word;continue}if(line){result.push(line);line=''}if(this.ctx.measureText(word).width<=width){line=word;continue}const segments=typeof Intl.Segmenter==='function'?[...new Intl.Segmenter(undefined,{granularity:'grapheme'}).segment(word)].map(s=>s.segment):[...word];for(const char of segments){if(this.ctx.measureText(line+char).width>width){result.push(line);line=''}line+=char}}result.push(line)}return result}
  /** A row can span pages; no max-height clipping or fixed nine-page assumptions. */
  row(label,text,accent=false){this.font(14);const lines=this.lines(text,865);let first=true;while(lines.length){if(this.y+42>728)this.page(this.title+' · continued');this.font(11,true);const labels=this.lines(first?label:'continued',145);const room=Math.max(1,Math.floor((728-this.y-16)/23)),chunk=lines.splice(0,room),height=Math.max(40,chunk.length*23+16,labels.length*13+16);if(this.y+height>728)this.page(this.title+' · continued');this.ctx.fillStyle=accent?'#edf7f6':'#f3f6f8';this.ctx.fillRect(34,this.y,1054,height-3);this.font(11,true);this.ctx.fillStyle='#0a2746';labels.forEach((s,i)=>this.ctx.fillText(s,43,this.y+8+i*13));this.font(14);this.ctx.fillStyle='#1c3548';chunk.forEach((s,i)=>this.ctx.fillText(s,194,this.y+8+i*23));this.y+=height;first=false}}
  async photo(label,src){if(!src)return;if(this.y+240>728)this.page(this.title+' · continued');const image=await new ImageService().load(src);this.font(13,true);this.ctx.fillStyle='#0a2746';this.ctx.fillText(label,34,this.y);this.y+=24;const scale=Math.min(1040/image.naturalWidth,205/image.naturalHeight);this.ctx.drawImage(image,34,this.y,image.naturalWidth*scale,image.naturalHeight*scale);this.y+=220}
  /** Build only requested sections. Empty evidence and unused signature cards are suppressed. */
  async build(record,mode='full'){await this.fonts();this.record=U.clone(record);this.pages=[];const r=this.record,c=this.coverage.compute(r);
    if(['full','summary'].includes(mode)){this.page('Executive summary');this.row('Factory / Buyer',`${r.meta.factory||'—'} / ${r.meta.buyer||'—'}`);this.row('Readiness',`Coverage ${c.coverage}% · Closure ${c.closure}% · Critical blockers ${c.criticalBlockers} · Release ${r.release.decision||'Not decided'}`,true);for(const [key,value] of Object.entries(r.meta)){if(value&&key!=='factory'&&key!=='buyer')this.row(key,Array.isArray(value)?value.join(', '):value)}const present=Object.entries(r.participants).filter(([,p])=>p.present);this.row('Participants',present.map(([role,p])=>`${role}: ${p.name||'—'}`).join('\n')||'None recorded');this.row('Release conditions',r.release.notes||'None recorded');await this.photo('Approved style / PP sample',r.photos.style)}
    if(['full','checklist'].includes(mode)){for(const section of this.relevance.sections(r)){const items=section.items.filter(i=>this.relevance.applies(i,r));if(!items.length)continue;this.page(section.title);for(const item of items){this.row(`${item[0]} · ${r.statuses[item[0]]||'OPEN'}${item[0].startsWith('CUST-')?' · CUSTOM':''}${item[2]?' · CRITICAL':''}`,this.locale.checkpoint(item[0],item[1]),!!item[2]);if(r.remarks[item[0]])this.row('Note / evidence',r.remarks[item[0]])}}if(r.measurements.some(m=>Object.values(m).some(Boolean))){this.page('Critical POM / measurement control');for(const m of r.measurements.filter(m=>Object.values(m).some(Boolean)))this.row('POM',`${m.pom||'—'}\nSpec: ${m.spec} · Tolerance: ${m.tol}\nMethod: ${m.method} · Risk: ${m.risk}\n${m.remark}`)}}
    if(['full','actions'].includes(mode)){this.page('Action tracker');if(!r.actions.length)this.row('Actions','No tracked actions.');for(const a of r.actions){this.row(`${a.checkpointId} · ${a.status}`,`${this.locale.checkpoint(a.checkpointId,a.issue)}\nAction: ${a.action||'—'}\nOwner: ${a.owner||'—'} · Due: ${a.dueDate||'—'}\nEvidence: ${a.evidence||'—'}`,a.status!=='Closed')}}
    const evidence=EVIDENCE_SLOTS.filter(([id])=>r.photos.evidence[id]);if(mode==='evidence'||mode==='full'&&evidence.length){this.page('Photo evidence');if(!evidence.length)this.row('Evidence','No evidence attached.');for(const [id,label] of evidence)await this.photo(label,r.photos.evidence[id])}
    if(['full','summary'].includes(mode)){const signs=SIGNATURE_ROLES.filter(([id])=>r.signatures[id]?.image||r.signatures[id]?.name);if(signs.length){this.page('Authorization & sign-off');for(const [id,label]of signs){const s=r.signatures[id];this.row(label,`${s.name||'—'} · ${s.designation||'—'} · ${s.date||'—'} ${s.time||''}`);await this.photo('Signature',s.image)}}}
    this.pages.forEach((canvas,i)=>{this.ctx=canvas.getContext('2d');this.font(11);this.ctx.fillStyle='#637588';this.ctx.fillText('Powered by EGENVA',34,760);this.ctx.fillText(`Page ${i+1} of ${this.pages.length}`,996,760);this.ctx.save();this.ctx.globalAlpha=.035;this.font(55,true);this.ctx.translate(290,460);this.ctx.rotate(-.25);this.ctx.fillText('VESA Enterprise Inc.',0,0);this.ctx.restore()});return this.pages;
  }
  /** Generate a real downloadable file; caller owns download/native share activation. */
  async pdf(record,mode){const pages=await this.build(record,mode),pdf=await PDFLib.PDFDocument.create();pdf.setTitle(`VESA PPM ${record.meta.style||record.id}`);pdf.setProducer(`VESA PPM ${APP_VERSION} · Powered by EGENVA`);for(const canvas of pages){const img=await pdf.embedJpg(canvas.toDataURL('image/jpeg',.94)),page=pdf.addPage([841.89,595.28]);page.drawImage(img,{x:0,y:0,width:841.89,height:595.28})}return new Blob([await pdf.save()],{type:'application/pdf'})}
  /** CSV neutralizes spreadsheet formula prefixes in every untrusted cell. */
  csv(record){const rows=[['Ref','Issue','Action','Owner','Due Date','Evidence','Status'],...record.actions.map(a=>[a.checkpointId,this.locale.checkpoint(a.checkpointId,a.issue),a.action,a.owner,a.dueDate,a.evidence,a.status])];return new Blob(['\ufeff'+rows.map(row=>row.map(v=>'"'+String(v||'').replace(/^[\s]*[=+@-]/,s=>"'"+s).replaceAll('"','""')+'"').join(',')).join('\r\n')],{type:'text/csv;charset=utf-8'})}
}
