'use strict';
/** V5 workspace orchestration. Extends the audited V4 engines rather than duplicating
 * relevance or release rules. Owns active-record transitions, UI shell and save queue.
 * RecordHistory/BackupCodec/RecoveryRepository/ReportService are injected owners.
 * All external communications require an explicit user click; no telemetry is sent. */
class V5Workspace extends AppController {
  constructor(){const planning=new PlanningService(),relevance=new RelevanceEngine(),coverage=new CoverageEngine(relevance),validation=new ValidationEngine(relevance,coverage,planning);super(new PpmRepository(),relevance,coverage,validation,new FormRenderer(relevance,coverage),new ImageService(),new ActionTrackerManager());this.planning=planning;this.meetingControls=new MeetingControls(this,planning);this.codec=new BackupCodec();this.history=new RecordHistory();this.recovery=new RecoveryRepository();this.locale=new LocaleService();this.reports=new ReportService(relevance,coverage,this.locale,planning);this.saveQueue=Promise.resolve();this.savedStamp=null;this.production=false;this.training=false;this.reportMode='full';this.lastSnapshot='';this.recoveryWarning=false;this.busy=false;this.pdfFile=null}
  /** Initialize storage and existing record without creating a phantom production draft. */
  async start(){await this.repo.init();try{await this.recovery.init()}catch{this.recoveryWarning=true}let last=null;try{last=await this.repo.get(this.repo.getActiveId());if(last)last=this.codec.decode(last)}catch(e){this.startWarning='We could not open the last saved meeting. Choose a saved PPM or open a saved copy'}this.record=last||PpmRecordFactory.create();this.production=!!last;this.savedStamp=last?.updatedAt||null;this.ensureCompatibility();this.shell();this.meetingControls.mount();this.buildStatic();this.renderAll();this.bindGlobal();this.bindWorkspace();this.history.reset(this.record);this.locale.set(this.locale.language);await this.home(true);this.registerWorker()}
  /** Install touch-safe shell once. Data-derived text is always escaped or assigned as text. */
  shell(){const bar=document.createElement('nav');bar.id='fileMenu';bar.setAttribute('aria-label','Application menu');bar.innerHTML=`<button data-command="home">HOME</button>${['File','Edit','View','Tools','Help'].map(x=>`<button data-menu="${x}">${x.toUpperCase()}</button>`).join('')}<span class="menu-spacer"></span><label>Sentences <select class="language-select" aria-label="Sentence language">${this.languageOptions()}</select></label><span class="version">V${APP_VERSION}</span>`;document.querySelector('.topbar').after(bar);const home=document.createElement('section');home.id='homeScreen';document.body.prepend(home);const banner=document.createElement('div');banner.id='trainingBanner';banner.innerHTML='<strong>DEMO · TRAINING ONLY</strong><button data-command="home">BACK TO HOME</button><button data-command="new">START NEW PPM</button><button data-command="profile-copy">USE THIS PROFILE FOR NEW PPM</button>';bar.after(banner);const recovery=document.createElement('div');recovery.id='storageBanner';bar.after(recovery);document.querySelector('#modalBackdrop .modal').setAttribute('role','dialog');document.querySelector('#modalBackdrop .modal').setAttribute('aria-modal','true')}
  languageOptions(){return [['en','English'],['bn','বাংলা'],['hi','हिन्दी'],['ta','தமிழ்']].map(([v,t])=>`<option value="${v}" ${v===this.locale.language?'selected':''}>${t}</option>`).join('')}
  /** Top-level capture guard blocks edits on finalized records before legacy handlers run. */
  bindWorkspace(){document.addEventListener('click',e=>{const b=e.target.closest('[data-command],[data-menu],[data-custom-add],[data-custom-edit],[data-custom-delete]');if(!b)return;e.preventDefault();e.stopImmediatePropagation();if(b.dataset.menu)this.menu(b.dataset.menu);else if(b.dataset.customAdd)this.customEditor(b.dataset.customAdd);else if(b.dataset.customEdit)this.customEditor('',b.dataset.customEdit);else if(b.dataset.customDelete)this.removeCustom(b.dataset.customDelete);else this.command(b.dataset.command).catch(err=>this.toast(err.message))},true);
    for(const type of ['input','change','click'])document.addEventListener(type,e=>{if(!this.record.locked&&this.planning.changes.diff(this.record).length&&e.target.closest('#signatures-section')){e.preventDefault();e.stopImmediatePropagation();this.toast('Review the changes before adding fresh signatures.');return}if(!this.record.locked||!e.target.closest('.app-shell'))return;const control=e.target.closest('button,input,select,textarea,canvas');if(!control)return;const permitted=control.closest('#fileMenu')||control.id==='checkpointSearch'||control.matches('[data-target],[data-filter],[data-mode],[data-hint],[data-knowledge],[data-remark-toggle]')||['finalizeBtn','printBtn','draftsBtn','moreBtn','knowledgeBtn','jumpUnreviewed','jumpActions'].includes(control.id);if(!permitted){e.preventDefault();e.stopImmediatePropagation();this.populateBindings();this.toast('Unlock the finalized record before editing.')}},true);
    document.addEventListener('change',e=>{if(e.target.matches('.language-select'))this.changeLanguage(e.target.value)});
    // Measurement/action fields previously saved only on blur; input now protects close-after-typing.
    document.addEventListener('input',e=>{if(this.record.locked)return;if(e.target.matches('[data-measure]'))this.updateMeasurement(e.target);if(e.target.matches('[data-action-field]'))this.updateAction(e.target);if(e.target.matches('[data-sig-name],[data-sig-designation],[data-sig-date],[data-sig-time]'))this.updateSignatureMeta(e.target)});
    document.addEventListener('keydown',e=>{if((e.ctrlKey||e.metaKey)&&e.key.toLowerCase()==='s'){e.preventDefault();this.save(true)}if(e.key==='Escape')this.closeModal();if((e.ctrlKey||e.metaKey)&&!e.target.matches('input,textarea')&&e.key.toLowerCase()==='z'){e.preventDefault();this.undo(e.shiftKey?1:-1)}});
    window.addEventListener('pagehide',()=>this.emergency());document.addEventListener('visibilitychange',()=>{if(document.hidden)this.emergency()});
    document.getElementById('modalBackdrop').addEventListener('click',e=>{if(e.target.id==='modalBackdrop')this.closeModal()});
    document.getElementById('modalBackdrop').addEventListener('keydown',e=>{if(e.key!=='Tab')return;const nodes=[...e.currentTarget.querySelectorAll('button,input,select,textarea,a[href]')].filter(x=>!x.disabled&&x.offsetParent);if(!nodes.length)return;const first=nodes[0],last=nodes.at(-1);if(e.shiftKey&&document.activeElement===first){e.preventDefault();last.focus()}else if(!e.shiftKey&&document.activeElement===last){e.preventDefault();first.focus()}})
  }
  /** Show recent records using either IndexedDB records or fallback index metadata. */
  async home(skipSave=false){if(!skipSave&&this.production&&!await this.save())return;this.closeModal();document.body.classList.add('at-home');const rows=await this.repo.list();const h=document.getElementById('homeScreen');h.innerHTML=`<header><img src="../../assets/vesa-logo-black.png" alt="VESA Enterprise Inc."><span>VESA Enterprise Inc.<small>PPM 360 · V${APP_VERSION}</small></span><select class="language-select" aria-label="Sentence language">${this.languageOptions()}</select></header><main><div class="home-intro"><span class="eyebrow">PRE-PRODUCTION MEETING</span><h1 data-sentence="Every detail. Ready for production.">Every detail. Ready for production.</h1><p data-sentence="homeIntro">Start a meeting, continue your work, or learn with the training demo.</p></div><div class="home-cards">${this.production?'<button data-command="continue"><b>Continue Last PPM</b><span>'+U.esc(this.record.meta.style||'Untitled style')+'</span></button>':''}<button data-command="new"><b>+ New PPM</b><span data-sentence="newHint">Start a blank production meeting.</span></button><button data-command="demo"><b>View Demo</b><span data-sentence="demoHint">Practice with a filled T-shirt example.</span></button><button data-command="restore"><b>Open Saved Copy</b><span data-sentence="restoreHint">Choose a PPM copy you previously downloaded.</span></button></div><div class="recent-heading"><h2>Recent PPMs</h2><button class="soft-btn" data-command="storage">Saved Work</button></div><div id="recentList">${rows.length?rows.map(r=>this.recentRow(r)).join(''):'<p data-sentence="noRecords">No saved production meetings yet.</p>'}</div><p class="local-note" data-sentence="localNotice">Your work is saved on this device. Download a saved copy so you can open it again or move it to another device.</p>${this.startWarning?`<p class="warning">${U.esc(this.startWarning)}. Your original saved records have not been deleted.</p>`:''}<footer>Powered by EGENVA</footer></main>`;h.querySelectorAll('[data-record-open]').forEach(b=>b.onclick=()=>this.openRecord(b.dataset.recordOpen));h.querySelectorAll('[data-record-delete]').forEach(b=>b.onclick=()=>this.deleteRecord(b.dataset.recordDelete));this.translate();this.recoveryNotice()}
  recentRow(r){const m=r.meta||r;return `<article class="recent-row"><div><strong>${U.esc(m.style||'Untitled style')}</strong><p>${U.esc(m.buyer||'No buyer')} · ${U.esc(m.factory||'No factory')} · PO ${U.esc(m.po||'—')}</p><small>${U.esc(new Date(r.updatedAt).toLocaleString())} · ${r.locked?'Finalized':'Draft'}</small></div><div><button class="soft-btn" data-record-open="${U.esc(r.id)}">OPEN</button><button class="danger-btn" data-record-delete="${U.esc(r.id)}">DELETE</button></div></article>`}
  showEditor(){document.body.classList.remove('at-home');document.body.classList.toggle('training',this.training);this.closeModal();requestAnimationFrame(()=>{for(const pad of this.signaturePads.values())pad.resize();this.restoreSignatures()});this.translate();this.recoveryNotice()}
  /** Replace record only after successful save/validation; reset all record-scoped history. */
  ensureCompatibility(){super.ensureCompatibility();this.planning.ensure(this.record);if(!this.record.changeReview.baseline&&(this.record.locked||['GO','CONDITIONAL GO'].includes(this.record.release.decision)))this.planning.changes.review(this.record,'Opened saved meeting','Starting point from the saved meeting on this device.')}
  activate(r,production=true,training=false){this.record=r;this.production=production;this.training=training;this.savedStamp=production?r.updatedAt:null;this.lastSnapshot='';this.ensureCompatibility();this.buildStatic();this.renderAll();this.history.reset(r);this.showEditor();window.scrollTo(0,0)}
  async openRecord(id){try{if(this.production&&!await this.save())return;const data=await this.repo.get(id);const r=this.codec.decode(data);await this.codec.verifyImages(r);this.activate(r);this.repo.setActiveId(id)}catch(e){this.toast(e.message)}}
  deleteRecord(id){this.openConfirm('Delete this saved PPM?','Download a saved copy before deleting. Earlier saved versions are kept separately.',async()=>{await this.repo.remove(id);if(this.record.id===id){this.production=false;this.training=false;this.record=PpmRecordFactory.create();this.savedStamp=null;this.repo.setActiveId('')}await this.home()})}
  async newRecord(){if(this.production&&!await this.save())return;this.activate(PpmRecordFactory.create(),true);this.savedStamp=null;await this.save(true);this.toast('New PPM created.')}
  async loadDemo(){if(this.production&&!await this.save())return;const r=new DemoDataBuilder(this.relevance).build();r.training=true;this.activate(r,false,true);this.toast('Training only. Demo changes are not saved to Recent PPMs.')}
  async duplicateRecord(){if(this.training)return this.profileCopy();const r=U.clone(this.record);if(!await this.save())return;r.id=U.uid();r.createdAt=r.updatedAt=new Date().toISOString();r.locked=false;r.signatures={};r.release={decision:'',notes:''};r.lastBackupAt='';this.activate(r,true);this.savedStamp=null;await this.save(true);this.toast('Saved as a new copy. Sign-off and release require fresh approval.')}
  async profileCopy(){const profile=this.record.meta.profile;await this.newRecord();if(this.record.meta.profile!==profile){this.record.meta.profile=profile;this.applyProfileDefaults(profile);this.renderAll();this.mutate()}}
  /** Queue immutable snapshots. Lock API serializes cross-tab writes when supported.
   * Optimistic timestamp check refuses to overwrite a record changed in another tab. */
  save(force=false){if(!this.production||this.training){this.setSaveState(this.training?'Training · not saved':'Ready');return Promise.resolve(true)}const r=U.clone(this.record);const raw=JSON.stringify(r);this.saveQueue=this.saveQueue.catch(()=>false).then(async()=>{const write=async()=>{try{const existing=await this.repo.get(r.id);if(existing&&this.savedStamp&&existing.updatedAt!==this.savedStamp)throw Error('This PPM was changed in another open window. Download a saved copy, then reopen the saved PPM.');await this.repo.save(r);if(this.record.id===r.id){this.record.updatedAt=r.updatedAt;this.savedStamp=r.updatedAt;this.lastSnapshot=JSON.stringify(this.record);this.repo.setActiveId(r.id)}this.setSaveState(this.repo.memoryOnly&&this.repo.fallback?'NOT SAVED · download a copy now':`Saved ${U.nowTime()}`);if(this.repo.memoryOnly&&this.repo.fallback)throw Error('Your work cannot be saved on this device right now. Download a saved copy before leaving.');try{await this.recovery.save(r,force);this.recoveryWarning=false}catch{this.recoveryWarning=true}this.recoveryNotice();return true}catch(e){this.setSaveState('SAVE FAILED');this.toast(e.message);return false}};return navigator.locks?navigator.locks.request('vesa-ppm-write',write):write()});return this.saveQueue}
  /** Small synchronous emergency copy supplements (not replaces) asynchronous autosave. */
  emergency(){if(!this.production||this.training)return;try{const raw=this.codec.encode(this.record);if(raw.length<2*1024*1024)sessionStorage.setItem('vesa.ppm.emergency',raw)}catch{}}
  mutate(rerender=true){if(this.record.locked)return;this.planning.ensure(this.record);if(this.planning.invalidate(this.record)){this.restoreSignatureMeta();for(const pad of this.signaturePads.values()){pad.restore('');pad.ctx.clearRect(0,0,pad.canvas.width,pad.canvas.height)}this.toast('Meeting details changed. Review the changes and collect fresh release approval and signatures.')}this.history.capture(this.record);super.mutate(rerender);this.meetingControls.update();this.translate()}
  undo(delta){if(this.record.locked){this.toast('Unlock before undo or redo.');return}const r=this.history.move(delta);if(!r){this.toast(delta<0?'Nothing to undo.':'Nothing to redo.');return}this.record=r;this.buildStatic();this.renderAll();this.save(true)}
  /** Full rebuild clears legacy image/signature remnants when records or resets change. */
  renderAll(){this.planning.ensure(this.record);if(this.training)this.record.training=true;super.renderAll();this.renderEvidence();this.bindEvidenceInputs();for(const [id,pad]of this.signaturePads){if(!this.record.signatures[id]?.image){pad.restore('');pad.ctx.clearRect(0,0,pad.canvas.width,pad.canvas.height)}}this.customControls();this.limitFields();this.meetingControls.update();this.translate()}
  limitFields(){document.querySelectorAll('[data-bind]').forEach(e=>e.maxLength=e.dataset.bind.endsWith('specialInstruction')||e.dataset.bind.endsWith('notes')?5000:500);document.querySelectorAll('[data-remark]').forEach(e=>e.maxLength=5000);document.querySelectorAll('[data-participant-name],[data-sig-name],[data-sig-designation]').forEach(e=>e.maxLength=200);document.querySelectorAll('[data-measure]').forEach(e=>e.maxLength=500);document.querySelectorAll('[data-action-field]').forEach(e=>{const k=e.dataset.actionField.split('.')[1];e.maxLength=k==='owner'?200:k==='evidence'?2000:5000})}
  updatePrintSummary(){} // Printing is explicit; large reports never run on every keystroke.
  preparePrint(){/* ReportService owns the prepared report; beforeprint must not overwrite it. */}
  updateLock(){super.updateLock();document.querySelectorAll('.quick-meta input,.release-btn,#removeStylePhoto,#addStylePhoto,#mobileAddStylePhoto,#addMeasurementRow,#pomPresetBtn').forEach(x=>x.disabled=!!this.record.locked);document.querySelectorAll('[data-custom-add],[data-custom-edit],[data-custom-delete]').forEach(x=>x.disabled=!!this.record.locked)}
  handleClick(e){const b=e.target.closest('button');if(b?.id==='addMeasurementRow'&&this.record.measurements.length>=100){this.toast('Maximum 100 measurement rows.');return}if(b?.id==='printBtn'){this.exportMenu();return}super.handleClick(e);this.customControls();this.limitFields();this.translate()}
  setBinding(el){if(this.record.locked)return;super.setBinding(el);this.customControls();this.translate()}
  toggleProcess(id){super.toggleProcess(id);this.customControls();this.translate()}
  applyFilter(){super.applyFilter();if(this.record.ui.hideNA)document.querySelectorAll('.checkpoint').forEach(row=>{if(this.record.statuses[row.dataset.id]==='N/A')row.style.display='none'})}
  /** Sentence translation is limited to owned checkpoint and explanatory DOM surfaces. */
  translate(){if(!this.locale)return;document.querySelectorAll('.language-select').forEach(s=>s.value=this.locale.language);for(const s of this.relevance.sections(this.record))for(const i of s.items){const row=document.querySelector(`.checkpoint[data-id="${i[0]}"]`);if(!row)continue;const label=this.locale.checkpoint(i[0],i[1]),title=row.querySelector('.cp-title');if(title?.firstChild)title.firstChild.textContent=label+' ';row.dataset.label=(label+' '+i[1]).toLowerCase();const hint=row.querySelector('.cp-hint');if(hint)hint.textContent=this.locale.sentence('hint-'+i[0],i[3]);}for(const s of SECTION_SCHEMA){document.querySelectorAll(`[data-knowledge-body="${s.id}"] li`).forEach((li,i)=>li.textContent=this.locale.sentence(`knowledge-${s.id}-${i}`,s.knowledge[i]))}document.querySelectorAll('[data-sentence]').forEach(el=>{if(!el.dataset.english)el.dataset.english=el.textContent;el.textContent=this.locale.sentence(el.dataset.sentence,el.dataset.english)});const scope=document.querySelector('#profileScopeIntel span');if(scope){const p=PROFILE_MAP[this.record.meta.profile]||PROFILE_MAP[''];scope.textContent=this.locale.sentence('profile-'+p.id,p.summary)+' '+this.locale.sentence('scopeExtra','Construction and process selections add their own relevant checks.')}this.record.actions.forEach((a,i)=>{const text=this.locale.checkpoint(a.checkpointId,a.issue);const td=document.querySelectorAll('#actionBody tr')[i]?.children[1];if(td)td.textContent=text;const mobile=document.querySelectorAll('#actionMobile .action-mobile>b')[i];if(mobile)mobile.textContent=(i+1)+'. '+text});document.querySelectorAll('.photo-placeholder b,.photo-placeholder span,.locked-banner,.release-btn small,#modalBody p,#modalBody li,#storageBanner').forEach(el=>{if(el.children.length||el.dataset.sentence||el.hasAttribute('data-live-result')||el.hasAttribute('data-entered-text'))return;const original=el.dataset.sourceSentence||el.textContent;if(PPM_SENTENCES[original]){el.dataset.sourceSentence=original;el.textContent=this.locale.sentence(original,original)}});document.querySelectorAll('.checkpoint .cp-title,.checkpoint .cp-hint,.section-knowledge').forEach(el=>el.lang=this.locale.language)}
  /** Knowledge paragraphs use the same section dictionaries as the meeting view. */
  openKnowledge(){this.openModal('PPM 360 Knowledge',`<div class="knowledge-grid">${SECTION_SCHEMA.map(s=>`<div class="knowledge-box"><h3>${U.esc(s.title)}</h3><ul>${s.knowledge.map((k,i)=>`<li data-sentence="knowledge-${s.id}-${i}">${U.esc(k)}</li>`).join('')}</ul></div>`).join('')}</div>`)}
  /** Preserve a recovery point before destructive reset/delete actions. */
  openConfirm(title,message,onYes){super.openConfirm(title,message,async()=>{if(this.record.locked&&title.startsWith('Reset'))return;if(this.production&&/^(Reset|Delete)/.test(title)){try{await this.recovery.save(this.record,true)}catch{this.toast('Earlier saved versions are unavailable. Download a saved copy to protect your work.')}}await onYes()})}
  /** UI wording boundary. Access: workspace toast calls; input is an error/message string.
   * Hides engine/parser diagnostics behind a useful retry instruction; translates approved
   * sentences only. Does not mutate meeting data or expose imported content as markup. */
  toast(msg){const text=String(msg);const plain=/JSON|IndexedDB|localStorage|QuotaExceeded|Unexpected token|Unexpected end|Cannot read|not a function|is not defined|Failed to (fetch|execute)|SyntaxError|transaction|object store|AbortError/i.test(text)?'We could not complete this step. Try again. If the problem continues, download a saved copy to protect your work.':text;super.toast(this.locale?.sentence(plain,plain)||plain)}
  changeLanguage(lang){this.locale.set(lang);this.translate();this.applyFilter();this.toast('Sentence language updated. Your entered data is unchanged.')}
  customControls(){for(const s of SECTION_SCHEMA){const sec=document.getElementById(s.id);if(!sec)continue;if(!sec.querySelector('[data-custom-add]')){const b=document.createElement('button');b.className='soft-btn custom-add';b.dataset.customAdd=s.id;b.textContent='+ ADD CHECKPOINT';sec.append(b)}}for(const c of this.record.customCheckpoints||[]){const row=document.querySelector(`.checkpoint[data-id="${c.id}"]`);if(row&&!row.querySelector('[data-custom-edit]')){const box=document.createElement('div');box.className='custom-tools';box.innerHTML=`<span class="tag">CUSTOM</span><button data-custom-edit="${c.id}">EDIT</button><button data-custom-delete="${c.id}">DELETE</button>`;row.querySelector('.cp-main>div:last-child').append(box)}}this.updateLock()}
  customEditor(section,id){if(this.record.locked)return;const c=(this.record.customCheckpoints||[]).find(x=>x.id===id);this.openModal(c?'Edit custom checkpoint':'Add checkpoint',`<p data-sentence="customHint">Custom text stays in the language you type. Master checkpoints remain protected.</p><label class="field">Checkpoint sentence<textarea id="customLabel" maxlength="500">${U.esc(c?.label||'')}</textarea></label><label class="field">Guidance<textarea id="customHint" maxlength="1500">${U.esc(c?.hint||'')}</textarea></label><label><input id="customCritical" type="checkbox" ${c?.critical?'checked':''}> Critical</label><button class="primary-btn" id="saveCustom">SAVE CHECKPOINT</button>`);document.getElementById('saveCustom').onclick=()=>{const label=document.getElementById('customLabel').value.trim();if(!label){this.toast('Enter a checkpoint sentence.');return}if(!c&&(this.record.customCheckpoints||[]).length>=100){this.toast('Maximum 100 custom checkpoints.');return}const value={id:c?.id||'CUST-'+crypto.randomUUID(),section:c?.section||section,label,hint:document.getElementById('customHint').value.trim(),critical:document.getElementById('customCritical').checked};this.record.customCheckpoints||=[];if(c)Object.assign(c,value);else{this.record.customCheckpoints.push(value);this.record.statuses[value.id]='';this.record.remarks[value.id]=''}const action=this.record.actions.find(a=>a.checkpointId===value.id);if(action)action.issue=label;this.closeModal();this.renderAll();this.mutate()}}
  removeCustom(id){if(this.record.locked)return;this.openConfirm('Delete custom checkpoint?','Its note and linked action will also be removed. Undo can restore them.',()=>{this.record.customCheckpoints=this.record.customCheckpoints.filter(c=>c.id!==id);delete this.record.statuses[id];delete this.record.remarks[id];this.record.actions=this.record.actions.filter(a=>a.checkpointId!==id);this.renderAll();this.mutate()})}
  /** Touch helper fills only the selected action; desktop/mobile duplicate inputs stay aligned. */
  renderActions(){super.renderActions();if(!this.record)return;document.querySelectorAll('[data-action-field$=".owner"]').forEach(el=>{el.setAttribute('list','participantNames')});let names=document.getElementById('participantNames');if(!names){names=document.createElement('datalist');names.id='participantNames';document.body.append(names)}names.innerHTML=Object.values(this.record.participants).filter(p=>p.present&&p.name).map(p=>`<option value="${U.esc(p.name)}"></option>`).join('');document.querySelectorAll('[data-action-field$=".dueDate"]').forEach(el=>{const box=document.createElement('div');box.className='quick-dates';for(const day of [0,1,2,3]){const b=document.createElement('button');b.type='button';b.textContent=day?'+'+day+'D':'TODAY';b.onclick=()=>{if(this.record.locked)return;const d=new Date();d.setDate(d.getDate()+day);el.value=`${d.getFullYear()}-${String(d.getMonth()+1).padStart(2,'0')}-${String(d.getDate()).padStart(2,'0')}`;this.updateAction(el)};box.append(b)}el.after(box)});document.querySelectorAll('[data-action-field$=".action"]').forEach(el=>{const b=document.createElement('button');b.textContent='QUICK ACTION';b.className='quick-action';b.onclick=()=>{if(this.record.locked)return;this.openModal('Select an action',['Verify against approved sample.','Submit for approval.','Correct and recheck.','Hold bulk until approved.'].map((t,i)=>`<button class="soft-btn" data-action-chip="${i}">${U.esc(this.locale.sentence(t,t))}</button>`).join(''));document.querySelectorAll('[data-action-chip]').forEach(chip=>chip.onclick=()=>{el.value=chip.textContent;this.updateAction(el);this.closeModal()})};el.after(b)})}
  updateAction(el){if(this.record.locked)return;super.updateAction(el);document.querySelectorAll('[data-action-field]').forEach(peer=>{if(peer!==el&&peer.dataset.actionField===el.dataset.actionField)peer.value=el.value})}
  /** Additive planning gates stay inside the existing release workflow. UI consumes the
   * same domain result; HOLD remains available. An accepted first GO establishes a point. */
  setRelease(value){super.setRelease(value);if(['GO','CONDITIONAL GO'].includes(value)&&this.record.release.decision===value&&!this.record.changeReview.baseline){this.planning.changes.review(this.record,'Release decision','Starting point recorded with the release decision.');this.save(true);this.meetingControls.update()}}
  updateReadiness(result){super.updateReadiness(result);const p=result.planning;if(!p)return;const list=document.getElementById('readinessList');for(const [label,ready] of [['Required approvals complete',!p.approvals.length],['Required measurements within tolerance',!p.measurements.length],['Changes reviewed',!p.changes.length]]){const li=document.createElement('li');li.innerHTML=`<span>${label}</span><b class="${ready?'pass':'fail'}">${ready?'READY':'OPEN'}</b>`;list.append(li)}}
  openValidation(target,result){super.openValidation(target,result);const list=document.querySelector('#modalBody ul'),p=result.planning;if(!list||!p)return;for(const text of [...p.approvals.map(a=>a.label+': '+a.message),...p.measurements.map(m=>m.label+': '+m.result.status),...(p.changes.length?['Review '+p.changes.length+' changed meeting details in What Changed?.']:[])]){const li=document.createElement('li');li.textContent=text;list.append(li)}}
  async openDrafts(){await this.home()}
  openTools(){this.menu('File')}
  menu(name){const options={File:[['new','New PPM'],['home','Open Saved PPM'],['save','Save Now'],['copy','Make Another Copy'],['backup','Download Saved Copy'],['restore','Open Saved Copy'],['export','Reports / Print / Share'],['home','Back to Home']],Edit:[['undo','Undo'],['redo','Redo'],['recovery','Earlier Saved Versions'],['reset','Reset Form']],View:[['fast','Fast Meeting'],['full','360° View'],['filter-all','All checkpoints'],['filter-unreviewed','Unreviewed Only'],['filter-action','Actions Only'],['filter-critical','Critical Only'],['hide-na','Hide / Show reviewed N/A']],Tools:[['approvals','Approvals'],['measure-check','Measurement Check'],['changes','What Changed?'],['validate','Check Meeting Readiness'],['storage','Saved Work'],['knowledge','Knowledge Guide'],['demo','Training Demo'],['update','Check for Updates']],Help:[['guide','Quick Guide'],['feedback','Feedback / Report a Problem'],['version','App Version']]};this.openModal(name,`<div class="menu-grid">${options[name].map(([key,label])=>`<button class="soft-btn" data-command="${key}">${label}</button>`).join('')}</div>`)}
  /** Commands are finite trusted identifiers, never evaluated from imported data. */
  async command(cmd){if(['approvals','measure-check','changes'].includes(cmd))return this.meetingControls.open(cmd);if(cmd.startsWith('filter-')){this.activeFilter=cmd.slice(7);this.record.ui.filter=this.activeFilter;this.applyUiMode();this.closeModal();return}switch(cmd){case'home':return this.home();case'continue':this.showEditor();return;case'new':return this.newRecord();case'demo':return this.loadDemo();case'copy':return this.duplicateRecord();case'profile-copy':return this.profileCopy();case'save':await this.save(true);this.closeModal();return;case'backup':return this.backup();case'json':return this.backup('json');case'restore':document.getElementById('importInput').click();return;case'undo':this.undo(-1);return;case'redo':this.undo(1);return;case'recovery':return this.recoveryMenu();case'reset':if(!this.record.locked)this.confirmResetAll();return;case'fast':case'full':this.record.ui.mode=cmd;this.applyUiMode();this.closeModal();return;case'hide-na':this.record.ui.hideNA=!this.record.ui.hideNA;this.applyFilter();this.closeModal();this.save();return;case'validate':{const r=this.validation.readiness(this.record);if(r.go)this.openModal('Meeting Checks Complete','<p>All GO checks are complete. Authorized release is still required.</p>');else this.openValidation('GO',r);return}case'storage':return this.storage();case'knowledge':return this.openKnowledge();case'export':return this.exportMenu();case'feedback':return this.feedback();case'guide':this.openModal('Quick Guide','<ol><li data-sentence="guide1">Choose New PPM or open a saved meeting.</li><li data-sentence="guide2">Select the garment profile and processes, then review every applicable checkpoint.</li><li data-sentence="guide3">ACTION creates a follow-up. Set its owner, due date and corrective action.</li><li data-sentence="guide4">Add evidence and named signatures, validate, then record the release decision.</li><li data-sentence="guide5">Finalize the meeting, download a saved copy, and prepare a report to share.</li></ol>');return;case'version':this.openModal('App Version',`<p>VESA PPM 360 · ${APP_VERSION}</p><p>V4 universal checks + V5 workspace. English / বাংলা / हिन्दी / தமிழ் sentences.</p><p>Powered by EGENVA</p>`);return;case'update':await this.worker?.update();this.toast('Update check requested. Reopen the app after saving.');return}}
  download(blob,name){const a=document.createElement('a'),url=URL.createObjectURL(blob);a.href=url;a.download=name;a.click();setTimeout(()=>URL.revokeObjectURL(url),10000)}
  filename(ext){return `VESA_PPM_${(this.record.meta.style||'STYLE').replace(/[^a-z0-9_-]/gi,'_')}_${(this.record.meta.po||'PO').replace(/[^a-z0-9_-]/gi,'_')}.${ext}`}
  backup(ext='vesappm'){const r=U.clone(this.record);r.lastBackupAt=new Date().toISOString();this.download(new Blob([ext==='json'?JSON.stringify(r,null,2):this.codec.encode(r)],{type:'application/json'}),this.filename(ext));this.record.lastBackupAt=r.lastBackupAt;this.save();this.toast('Your saved copy is downloading. Keep it somewhere you can find it again.')}
  exportJson(){this.backup('json')}
  /** Imports always receive a new record ID; existing production records cannot be overwritten. */
  async importJson(e){const f=e.target.files?.[0];if(!f)return;try{if(f.size>BackupCodec.MAX_BYTES)throw Error('This saved copy is too large to open. Try a copy with fewer or smaller photos.');const r=this.codec.decode(JSON.parse(await f.text()));await this.codec.verifyImages(r);if(this.production&&!await this.save())return;r.id=U.uid();r.createdAt=r.updatedAt=new Date().toISOString();this.activate(r,!r.training,!!r.training);this.savedStamp=null;await this.save(true);this.toast('Your saved copy is open as a separate PPM. Your other meetings are unchanged.')}catch(err){this.toast(err instanceof SyntaxError?'We could not open this saved copy. Choose a PPM copy downloaded from this app.':err.message)}finally{e.target.value=''}}
  async recoveryMenu(){const rows=await this.recovery.list(this.record.id);let emergency=null;try{const raw=sessionStorage.getItem('vesa.ppm.emergency');if(raw){const r=this.codec.decode(JSON.parse(raw));if(r.id===this.record.id)emergency=r}}catch{}this.openModal('Earlier Saved Versions',`<p data-sentence="recoveryHint">Open an earlier saved version as a new meeting. Your current meeting stays unchanged.</p>${emergency?'<button class="soft-btn" id="restoreEmergency">OPEN RECENT UNSAVED WORK</button>':''}${rows.map((r,i)=>`<p><button class="soft-btn" data-recover="${i}">${U.esc(new Date(r.at).toLocaleString())} · ${U.esc(r.record.meta.style||'Untitled')}</button></p>`).join('')||'<p>No earlier saved versions yet.</p>'}`);const restore=async r=>{if(this.production&&!await this.save())return;r=this.codec.decode(r);r.id=U.uid();r.locked=false;r.signatures={};r.release={decision:'',notes:''};this.activate(r,true);this.savedStamp=null;await this.save(true)};document.querySelectorAll('[data-recover]').forEach(b=>b.onclick=()=>restore(rows[Number(b.dataset.recover)].record));const b=document.getElementById('restoreEmergency');if(b)b.onclick=()=>restore(emergency)}
  recoveryNotice(){const el=document.getElementById('storageBanner');if(!el)return;el.textContent=this.recoveryWarning?'Earlier saved versions are unavailable. Download a saved copy to protect your work.':this.production&&!this.record.lastBackupAt?'Keep a separate copy of your work: File → Download Saved Copy.':'';el.classList.toggle('visible',!!el.textContent)}
  /** Saved-work overview owns task wording, never exposes persistence-engine names.
   * Called by Tools/Home; reads counts and last download only. No storage mutation. */
  async storage(){const rows=await this.repo.list(),snapshots=await this.recovery.list(this.record.id);this.openModal('Saved Work',`<p>${this.repo.fallback&&this.repo.memoryOnly?'Your work cannot be kept after you close this app. Download a saved copy now.':'Your work is saved on this device.'}</p><p>Saved meetings: ${rows.length} · Earlier saved versions: ${snapshots.length}</p><p>Last saved copy downloaded: ${U.esc(this.record.lastBackupAt?new Date(this.record.lastBackupAt).toLocaleString():'Not yet downloaded')}</p><p data-sentence="localNotice">Your work is saved on this device. Download a saved copy so you can open it again or move it to another device.</p><button class="primary-btn" data-command="backup">DOWNLOAD SAVED COPY</button>`)}
  /** Prepared PDF is created before Share click so mobile transient activation is retained. */
  exportMenu(){this.pdfFile=null;this.openModal('Reports / Print / Share',`<label>Report <select id="reportMode"><option value="full">Full PPM Report</option><option value="summary">Meeting Summary</option><option value="actions">Action Tracker</option><option value="checklist">Checklist Report</option><option value="evidence">Photo Evidence</option><option value="approvals">Approvals</option><option value="measurements">Measurement Check</option><option value="changes">What Changed?</option></select></label><div class="menu-grid"><button class="primary-btn" id="makePdf">PREPARE REPORT</button><button class="soft-btn" id="printReportBtn">PRINT REPORT</button><button class="soft-btn" id="csvExport">DOWNLOAD ACTION LIST</button><button class="soft-btn" data-command="backup">DOWNLOAD SAVED COPY</button><button class="soft-btn" id="shareSummary">SHARE SUMMARY</button></div><p id="exportStatus" aria-live="polite"></p><div id="readyPdf"></div>`);document.getElementById('makePdf').onclick=async()=>{if(this.busy)return;this.busy=true;const status=document.getElementById('exportStatus'),button=document.getElementById('makePdf');button.disabled=true;status.textContent='Preparing your report…';try{const mode=document.getElementById('reportMode').value,blob=await this.reports.pdf(this.record,mode);this.pdfFile=new File([blob],this.filename(mode+'.pdf'),{type:'application/pdf'});status.textContent=`Your report is ready · ${this.reports.pages.length} pages`;document.getElementById('readyPdf').innerHTML='<button class="primary-btn" id="downloadPdf">DOWNLOAD REPORT</button> <button class="soft-btn" id="sharePdf">SHARE REPORT</button>';document.getElementById('downloadPdf').onclick=()=>this.download(this.pdfFile,this.pdfFile.name);document.getElementById('sharePdf').onclick=()=>this.sharePdf()}catch(e){status.textContent='We could not prepare this report. Try again or choose a shorter report.'}finally{this.busy=false;button.disabled=false}};document.getElementById('printReportBtn').onclick=async()=>{if(this.busy)return;this.busy=true;try{const mode=document.getElementById('reportMode').value;await this.reports.build(this.record,mode);const root=document.getElementById('printReport');root.replaceChildren(...this.reports.pages.map(c=>{const img=new Image();img.src=c.toDataURL('image/jpeg',.94);img.className='report-page';return img}));await Promise.all([...root.querySelectorAll('img')].map(i=>i.decode()));this.closeModal();window.print()}catch(e){this.toast(e.message)}finally{this.busy=false}};document.getElementById('csvExport').onclick=()=>this.download(this.reports.csv(this.record),this.filename('csv'));document.getElementById('shareSummary').onclick=()=>this.summaryShare()}
  async sharePdf(){if(!this.pdfFile)return;if(navigator.canShare?.({files:[this.pdfFile]})){try{await navigator.share({files:[this.pdfFile],title:'VESA PPM Report'})}catch(e){if(e.name!=='AbortError')this.toast('Sharing is unavailable. Download the report, then attach it to your message.')}}else{this.download(this.pdfFile,this.pdfFile.name);this.toast('Your report is downloading. Attach it to your email or WhatsApp message.')}}
  summaryShare(){const c=this.coverage.compute(this.record),r=this.record,text=`VESA PPM 360\nStyle: ${r.meta.style}\nPO: ${r.meta.po}\nFactory: ${r.meta.factory}\nCoverage: ${c.coverage}%\nOpen actions: ${r.actions.filter(a=>a.status!=='Closed').length}\nRelease: ${r.release.decision||'Not decided'}\n${r.release.notes}`;this.openModal('Share Summary',`<p>Review the summary before sharing.</p><textarea id="summaryText" rows="9">${U.esc(text)}</textarea><div class="menu-grid"><button class="soft-btn" id="copySummary">COPY</button><button class="soft-btn" id="nativeSummary">SHARE</button><a class="soft-btn" id="emailSummary">EMAIL</a><a class="soft-btn" id="waSummary" target="_blank" rel="noopener noreferrer">WHATSAPP</a></div>`);const value=()=>document.getElementById('summaryText').value;document.getElementById('copySummary').onclick=async()=>{try{await navigator.clipboard.writeText(value());this.toast('Summary copied.')}catch{this.toast('Select the text and copy it manually.')}};document.getElementById('nativeSummary').onclick=async()=>{try{if(navigator.share)await navigator.share({text:value()});else this.toast('Use Copy, Email or WhatsApp.')}catch(e){if(e.name!=='AbortError')this.toast(e.message)}};document.getElementById('emailSummary').onclick=e=>e.currentTarget.href='mailto:?subject='+encodeURIComponent('VESA PPM summary')+'&body='+encodeURIComponent(value());document.getElementById('waSummary').onclick=e=>e.currentTarget.href='https://wa.me/?text='+encodeURIComponent(value())}
  feedback(){this.openModal('Feedback / Report a Problem',`<p data-sentence="feedbackHint">How was this meeting? Feedback stays on this device until you download and share it.</p><label>Experience <select id="feedbackRating"><option>Easy</option><option>Okay</option><option>Difficult</option></select></label><label>Issue <select id="feedbackCategory">${['None','Too much typing','Hard to find section','Missing checkpoint','Checkpoint unclear','Problem saving or opening a copy','Report or printing problem','Slow','Other'].map(s=>'<option>'+s+'</option>').join('')}</select></label><textarea id="feedbackText" maxlength="1000" placeholder="Optional comment"></textarea><p>No buyer, style, PO, photos or signatures are included automatically.</p><button class="primary-btn" id="saveFeedback">SAVE FEEDBACK</button><button class="soft-btn" id="downloadFeedback">DOWNLOAD FEEDBACK</button>`);const entry=()=>({version:APP_VERSION,at:new Date().toISOString(),rating:document.getElementById('feedbackRating').value,category:document.getElementById('feedbackCategory').value,comment:document.getElementById('feedbackText').value,screen:`${innerWidth}x${innerHeight}`});document.getElementById('saveFeedback').onclick=()=>{try{const rows=JSON.parse(localStorage.getItem('vesa.ppm.feedback')||'[]');rows.push(entry());localStorage.setItem('vesa.ppm.feedback',JSON.stringify(rows.slice(-50)));this.toast('Feedback saved on this device.')}catch{this.toast('Could not save feedback. Use Download.')}};document.getElementById('downloadFeedback').onclick=()=>{const e=entry(),text=`VESA PPM Feedback\nDate: ${new Date(e.at).toLocaleString()}\nExperience: ${e.rating}\nProblem: ${e.category}\nComment: ${e.comment||'None'}\nApp version: ${e.version}\n`;this.download(new Blob([text],{type:'text/plain;charset=utf-8'}),'VESA_PPM_Feedback.txt')}}
  toggleFinalize(){const wasLocked=this.record.locked;super.toggleFinalize();if(!wasLocked){const yes=document.getElementById('confirmYes');if(yes){const original=yes.onclick;yes.onclick=()=>{original();if(this.record.locked){if(!this.record.changeReview.baseline)this.planning.changes.review(this.record,'Finalized meeting','Starting point recorded when this meeting was finalized.');this.history.reset(this.record);this.save(true);this.meetingControls.update();setTimeout(()=>this.feedback(),100)}}}}}
  openModal(title,html){this.meetingControls.dispose();this.previousFocus=document.activeElement;super.openModal(title,html);this.translate();setTimeout(()=>document.getElementById('modalClose').focus(),0)}
  closeModal(){this.meetingControls.dispose();super.closeModal();this.previousFocus?.focus?.()}
  /** App-scoped worker keeps offline assets isolated from the marketing site's cache. */
  async registerWorker(){if(!('serviceWorker'in navigator)||!/^https?:$/.test(location.protocol))return;try{this.worker=await navigator.serviceWorker.register('./service-worker.js',{scope:'./',updateViaCache:'none'});this.worker.addEventListener('updatefound',()=>{const next=this.worker.installing;next?.addEventListener('statechange',()=>{if(next.state==='installed'&&navigator.serviceWorker.controller)this.toast('Update available. Save your work and reopen the app.')})})}catch{this.toast('This app is not ready to work without internet yet. You can still use it online and download saved copies.')}
  }
}
const app=new V5Workspace();
app.start().catch(err=>{document.getElementById('saveState').textContent='STARTUP ERROR';const box=document.createElement('div');box.className='startup-error';box.textContent='PPM could not open. Your saved meetings have not been deleted. Refresh the page and try again.';document.body.prepend(box)});
